// ============================================================
//  music.js  —  音乐播放列表数据
//  请将此文件与 index.html 放在同一目录下
// ============================================================

const KOREA_DATA = [
{id: 1,title: '2NE1-Fire',artist: '2NE1',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/2NE1-Fire.mp3',duration: 300},
{id: 2,title: 'Baby V.O.X-Get Up',artist: 'Baby V.O.X',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/Baby V.O.X-Get Up.mp3',duration: 300},
{id: 3,title: 'Baby V.O.X-Killer',artist: 'Baby V.O.X',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/Baby V.O.X-Killer.mp3',duration: 300},
{id: 4,title: 'Baby V.O.X-Why',artist: 'Baby V.O.X',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/Baby V.O.X-Why.mp3',duration: 300},
{id: 5,title: 'Baby V.O.X-偶然',artist: 'Baby V.O.X',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/Baby V.O.X-偶然.mp3',duration: 300},
{id: 6,title: 'BoA-AmazingKiss',artist: 'BoA',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/BoA-AmazingKiss.mp3',duration: 300},
{id: 7,title: 'BoA-ListenToMyHeart',artist: 'BoA',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/BoA-ListenToMyHeart.mp3',duration: 300},
{id: 8,title: 'BoA-No1',artist: 'BoA',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/BoA-No1.mp3',duration: 300},
{id: 9,title: 'Dana-到世界尽头',artist: 'DanA',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/Dana-到世界尽头.mp3',duration: 300},
{id: 10,title: 'Davichi-爱情和战争',artist: 'Davichi',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/Davichi-爱情和战争.mp3',duration: 300},
{id: 11,title: 'Davichi-悲伤的约定',artist: 'Davichi',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/Davichi-悲伤的约定.mp3',duration: 300},
{id: 12,title: 'Davichi-即使恨也爱你',artist: 'Davichi',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/Davichi-即使恨也爱你.mp3',duration: 300},
{id: 13,title: 'Davichi-可笑的爱情',artist: 'Davichi',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/Davichi-可笑的爱情.mp3',duration: 300},
{id: 14,title: 'Davichi-这份爱',artist: 'Davichi',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/Davichi-这份爱.mp3',duration: 300},
{id: 15,title: 'DreamGirls殆死悲爱-ImSorry',artist: 'DreamGirls殆死悲爱',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/DreamGirls殆死悲爱-ImSorry.mp3',duration: 300},
{id: 16,title: 'Fin.K.L-BlueRain',artist: 'Fin.K.L',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/Fin.K.L-BlueRain.mp3',duration: 300},
{id: 17,title: 'i-dle-Queencard',artist: 'i-dle',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/i-dle-Queencard.mp3',duration: 300},
{id: 18,title: 'i-dle-TOMBOY',artist: 'i-dle',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/i-dle-TOMBOY.mp3',duration: 300},
{id: 19,title: 'jewelry-again',artist: 'jewelry',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/jewelry-again.mp3',duration: 300},
{id: 20,title: 'jewelry-Super_Star',artist: 'jewelry',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/jewelry-Super_Star.mp3',duration: 300},
{id: 21,title: 'Jewelry-更喜欢你',artist: 'Jewelry',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/Jewelry-更喜欢你.mp3',duration: 300},
{id: 22,title: 'Kara-Honey',artist: 'KarA',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/Kara-Honey.mp3',duration: 300},
{id: 23,title: 'kiss-因为是女子',artist: 'kiss',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/kiss-因为是女子.mp3',duration: 300},
{id: 24,title: 'Lyn-爱情都是谎言',artist: 'Lyn',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/Lyn-爱情都是谎言.mp3',duration: 300},
{id: 25,title: 'Lyn-歌信',artist: 'Lyn',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/Lyn-歌信.mp3',duration: 300},
{id: 26,title: 'Psy-江南Style',artist: 'Psy',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/Psy-江南Style.mp3',duration: 300},
{id: 27,title: 'rania-DrFeelGood',artist: 'raniA',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/rania-DrFeelGood.mp3',duration: 300},
{id: 28,title: 'S.E.S.-Dreams Come True',artist: 'S.E.S.',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/S.E.S.-Dreams Come True.mp3',duration: 300},
{id: 29,title: 'S.E.S.-Just In Love',artist: 'S.E.S.',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/S.E.S.-Just In Love.mp3',duration: 300},
{id: 30,title: 'S.E.S.-Love',artist: 'S.E.S.',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/S.E.S.-Love.mp3',duration: 300},
{id: 31,title: 'S.E.S.-Oh My Love',artist: 'S.E.S.',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/S.E.S.-Oh My Love.mp3',duration: 300},
{id: 32,title: 'S.E.S.-Sha-La-LA',artist: 'S.E.S.',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/S.E.S.-Sha-La-La.mp3',duration: 300},
{id: 33,title: 'S.E.S.-Twilight Zone',artist: 'S.E.S.',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/S.E.S.-Twilight Zone.mp3',duration: 300},
{id: 34,title: 'S.E.S.-U',artist: 'S.E.S.',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/S.E.S.-U.mp3',duration: 300},
{id: 35,title: 'sHarp-我的嘴唇如暖暖的咖啡',artist: 'sHarp',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/sHarp-我的嘴唇如暖暖的咖啡.mp3',duration: 300},
{id: 36,title: 'T-ara-DAY BY DAY',artist: 'T-arA',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/T-ara-DAY BY DAY.mp3',duration: 300},
{id: 37,title: 'T-ara-LoveyDovey',artist: 'T-arA',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/T-ara-LoveyDovey.mp3',duration: 300},
{id: 38,title: 'T-ara-Sexy Love',artist: 'T-arA',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/T-ara-Sexy Love.mp3',duration: 300},
{id: 39,title: 'WAX',artist: 'WAX',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/WAX.mp3',duration: 300},
{id: 40,title: 'WAX-Money',artist: 'WAX',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/WAX-Money.mp3',duration: 300},
{id: 41,title: 'WAX-改变化装',artist: 'WAX',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/WAX-改变化装.mp3',duration: 300},
{id: 42,title: 'WAX-渴望爱情',artist: 'WAX',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/WAX-渴望爱情.mp3',duration: 300},
{id: 43,title: 'WAX-一通电话也不行',artist: 'WAX',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/WAX-一通电话也不行.mp3',duration: 300},
{id: 44,title: 'WAX-余情',artist: 'WAX',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/WAX-余情.mp3',duration: 300},
{id: 45,title: 'WAX-只有眼泪只有眼泪',artist: 'WAX',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/WAX-只有眼泪只有眼泪.mp3',duration: 300},
{id: 46,title: 'WAX-坐着地铁',artist: 'WAX',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/WAX-坐着地铁.mp3',duration: 300},
{id: 47,title: 'WonderGirls-nobody',artist: 'WonderGirls',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/WonderGirls-nobody.mp3',duration: 300},
{id: 48,title: '白智英-不再爱了',artist: '白智英',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/白智英-不再爱了.mp3',duration: 300},
{id: 49,title: '白智英-那个女人',artist: '白智英',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/白智英-那个女人.mp3',duration: 300},
{id: 50,title: '白智英-像中枪一样',artist: '白智英',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/白智英-像中枪一样.mp3',duration: 300},
{id: 51,title: '蔡妍-My Love',artist: '蔡妍',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/蔡妍-My Love.mp3',duration: 300},
{id: 52,title: '蔡妍-两个人',artist: '蔡妍',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/蔡妍-两个人.mp3',duration: 300},
{id: 53,title: '蔡妍-危险的演出',artist: '蔡妍',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/蔡妍-危险的演出.mp3',duration: 300},
{id: 54,title: '蔡妍-摇摆',artist: '蔡妍',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/蔡妍-摇摆.mp3',duration: 300},
{id: 55,title: '冬季恋歌-从开始到现在',artist: '冬季恋歌',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/冬季恋歌-从开始到现在.mp3',duration: 300},
{id: 56,title: '高耀太-悲梦',artist: '高耀太',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/高耀太-悲梦.mp3',duration: 300},
{id: 57,title: '高耀太-波澜',artist: '高耀太',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/高耀太-波澜.mp3',duration: 300},
{id: 58,title: '高耀太-纯情',artist: '高耀太',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/高耀太-纯情.mp3',duration: 300},
{id: 59,title: '高耀太-飞翔',artist: '高耀太',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/高耀太-飞翔.mp3',duration: 300},
{id: 60,title: '高耀太-火花',artist: '高耀太',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/高耀太-火花.mp3',duration: 300},
{id: 61,title: '高耀太-失恋',artist: '高耀太',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/高耀太-失恋.mp3',duration: 300},
{id: 62,title: '高耀太-英雄',artist: '高耀太',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/高耀太-英雄.mp3',duration: 300},
{id: 63,title: '高耀太-诱惑',artist: '高耀太',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/高耀太-诱惑.mp3',duration: 300},
{id: 64,title: '洪真英-活着',artist: '洪真英',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/洪真英-活着.mp3',duration: 300},
{id: 65,title: '金智贤-呼唤1',artist: '金智贤',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/金智贤-呼唤1.mp3',duration: 300},
{id: 66,title: '李宝蓝-红豆2',artist: '李宝蓝',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/李宝蓝-红豆2.mp3',duration: 300},
{id: 67,title: '李海丽-红豆1',artist: '李海丽',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/李海丽-红豆1.mp3',duration: 300},
{id: 68,title: '李孝利-10minutes',artist: '李孝利',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/李孝利-10minutes.mp3',duration: 300},
{id: 69,title: '李秀英-AlsoILoveYou',artist: '李秀英',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/李秀英-AlsoILoveYou.mp3',duration: 300},
{id: 70,title: '李秀英-NEVERAGAIN',artist: '李秀英',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/李秀英-NEVERAGAIN.mp3',duration: 300},
{id: 71,title: '李秀英-我们',artist: '李秀英',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/李秀英-我们.mp3',duration: 300},
{id: 72,title: '李贞贤-阿里阿里',artist: '李贞贤',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/李贞贤-阿里阿里.mp3',duration: 300},
{id: 73,title: '李贞贤-半',artist: '李贞贤',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/李贞贤-半.mp3',duration: 300},
{id: 74,title: '李贞贤-发疯',artist: '李贞贤',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/李贞贤-发疯.mp3',duration: 300},
{id: 75,title: '李贞贤-换掉',artist: '李贞贤',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/李贞贤-换掉.mp3',duration: 300},
{id: 76,title: '李贞贤-哇',artist: '李贞贤',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/李贞贤-哇.mp3',duration: 300},
{id: 77,title: '李贞贤-月亮啊月亮',artist: '李贞贤',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/李贞贤-月亮啊月亮.mp3',duration: 300},
{id: 78,title: '柳真-ChaChA',artist: '柳真',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/柳真-ChaCha.mp3',duration: 300},
{id: 79,title: '米娜-Kiss Kiss',artist: '米娜',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/米娜-Kiss Kiss.mp3',duration: 300},
{id: 80,title: '米娜-电话情缘',artist: '米娜',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/米娜-电话情缘.mp3',duration: 300},
{id: 81,title: '米娜-转',artist: '米娜',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/米娜-转.mp3',duration: 300},
{id: 82,title: '裴勇俊-MyMemory',artist: '裴勇俊',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/裴勇俊-MyMemory.mp3',duration: 300},
{id: 83,title: '朴惠京-RAIN',artist: '朴惠京',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/朴惠京-RAIN.mp3',duration: 300},
{id: 84,title: '朴慧京-yesterday',artist: '朴慧京',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/朴慧京-yesterday.mp3',duration: 300},
{id: 85,title: '朴慧京-结婚',artist: '朴慧京',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/朴慧京-结婚.mp3',duration: 300},
{id: 86,title: '朴孝信-花信',artist: '朴孝信',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/朴孝信-花信.mp3',duration: 300},
{id: 87,title: '朴孝信-雪之花',artist: '朴孝信',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/朴孝信-雪之花.mp3',duration: 300},
{id: 88,title: '朴志胤-Steal Away',artist: '朴志胤',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/朴志胤-Steal Away.mp3',duration: 300},
{id: 89,title: '朴志胤-成人礼',artist: '朴志胤',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/朴志胤-成人礼.mp3',duration: 300},
{id: 90,title: '少女时代-Animal',artist: '少女时代',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-Animal.mp3',duration: 300},
{id: 91,title: '少女时代-BeepBeep',artist: '少女时代',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-BeepBeep.mp3',duration: 300},
{id: 92,title: '少女时代-GalaxySupernovA',artist: '少女时代',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-GalaxySupernova.mp3',duration: 300},
{id: 93,title: '少女时代-Gee(Japanesever.)',artist: '少女时代',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-Gee(Japanesever.).mp3',duration: 300},
{id: 94,title: '少女时代-Gee',artist: '少女时代',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-Gee.mp3',duration: 300},
{id: 95,title: '少女时代-Holiday',artist: '少女时代',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-Holiday.mp3',duration: 300},
{id: 96,title: '少女时代-HOOT',artist: '少女时代',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-HOOT.mp3',duration: 300},
{id: 97,title: '少女时代-IntoTheNewWorld',artist: '少女时代',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-IntoTheNewWorld.mp3',duration: 300},
{id: 98,title: '少女时代-Mr.Mr.(Japanesever.)',artist: '少女时代',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-Mr.Mr.(Japanesever.).mp3',duration: 300},
{id: 99,title: '少女时代-MrTaxi',artist: '少女时代',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-MrTaxi.mp3',duration: 300},
{id: 100,title: '少女时代-Oh!(Japanesever.)',artist: '少女时代',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-Oh!(Japanesever.).mp3',duration: 300},
{id: 101,title: '少女时代-Oh!',artist: '少女时代',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-Oh!.mp3',duration: 300},
{id: 102,title: '少女时代-Paparazzi',artist: '少女时代',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-Paparazzi.mp3',duration: 300},
{id: 103,title: '少女时代-PARTY',artist: '少女时代',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-PARTY.mp3',duration: 300},
{id: 104,title: '少女时代-RunDevilRun',artist: '少女时代',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-RunDevilRun.mp3',duration: 300},
{id: 105,title: '少女时代-TheBoys',artist: '少女时代',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-TheBoys.mp3',duration: 300},
{id: 106,title: '申彗星-LoveLetter',artist: '申彗星',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/申彗星-LoveLetter.mp3',duration: 300},
{id: 107,title: '申彗星-爱情病',artist: '申彗星',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/申彗星-爱情病.mp3',duration: 300},
{id: 108,title: '申彗星-我慢慢死去',artist: '申彗星',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/申彗星-我慢慢死去.mp3',duration: 300},
{id: 109,title: '申彗星-在那个位置',artist: '申彗星',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/申彗星-在那个位置.mp3',duration: 300},
{id: 110,title: '申升勋-我相信',artist: '申升勋',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/申升勋-我相信.mp3',duration: 300},
{id: 111,title: '淑熙-啦啦啦',artist: '淑熙',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/淑熙-啦啦啦.mp3',duration: 300},
{id: 112,title: '宋雨琦-Radio',artist: '宋雨琦',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/宋雨琦-Radio.mp3',duration: 300},
{id: 113,title: '孙丹菲-星期六晚上',artist: '孙丹菲',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/孙丹菲-星期六晚上.mp3',duration: 300},
{id: 114,title: '太妍-如果',artist: '太妍',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/太妍-如果.mp3',duration: 300},
{id: 115,title: '太妍-四季',artist: '太妍',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/太妍-四季.mp3',duration: 300},
{id: 116,title: '吴贤兰-Remember',artist: '吴贤兰',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/吴贤兰-Remember.mp3',duration: 300},
{id: 117,title: '孝琳-再见',artist: '孝琳',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/孝琳-再见.mp3',duration: 300},
{id: 118,title: '严正花-都走吧',artist: '严正花',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/严正花-都走吧.mp3',duration: 300},
{id: 119,title: '玉珠铉-仲夏夜之梦',artist: '玉珠铉',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/玉珠铉-仲夏夜之梦.mp3',duration: 300},
{id: 120,title: '张娜拉-Sweet Dream',artist: '张娜拉',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/张娜拉-Sweet Dream.mp3',duration: 300},
{id: 121,title: '郑日英-祈祷',artist: '郑日英',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/郑日英-祈祷.mp3',duration: 300}
];

// 如果需要在其他环境中使用，也可导出
// 浏览器环境中直接使用全局变量 MUSIC_DATA
if (typeof module !== 'undefined' && module.exports) {
  module.exports = MUSIC_DATA;
}