// ============================================================
//  music.js  —  音乐播放列表数据
//  请将此文件与 index.html 放在同一目录下
// ============================================================

const KOREA_DATA = [
{id: 197,title: 'BoA-AmazingKiss',artist: 'BoA',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/BoA-AmazingKiss.mp3',duration: 300},
{id: 196,title: 'BoA-No1',artist: 'BoA',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/BoA-No1.mp3',duration: 300},
{id: 1,title: 'Dana-到世界尽头',artist: 'DanA',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/Dana-到世界尽头.mp3',duration: 300},
{id: 2,title: 'davichi-爱情和战争',artist: 'davichi',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/davichi-爱情和战争.mp3',duration: 300},
{id: 3,title: 'davichi-悲伤的约定',artist: 'davichi',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/davichi-悲伤的约定.mp3',duration: 300},
{id: 4,title: 'davichi-即使恨也爱你',artist: 'davichi',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/davichi-即使恨也爱你.mp3',duration: 300},
{id: 5,title: 'Davichi-可笑的爱情',artist: 'Davichi',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/Davichi-可笑的爱情.mp3',duration: 300},
{id: 6,title: 'DreamGirls殆死悲爱-ImSorry',artist: 'DreamGirls殆死悲爱',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/DreamGirls殆死悲爱-ImSorry.mp3',duration: 300},
{id: 7,title: 'Fin.K.L-BlueRain',artist: 'Fin.K.L',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/Fin.K.L-BlueRain.mp3',duration: 300},
{id: 8,title: 'jewelry-again',artist: 'jewelry',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/jewelry-again.mp3',duration: 300},
{id: 9,title: 'jewelry-Super_Star',artist: 'jewelry',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/jewelry-Super_Star.mp3',duration: 300},
{id: 10,title: 'Jewelry-更喜欢你',artist: 'Jewelry',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/Jewelry-更喜欢你.mp3',duration: 300},
{id: 11,title: 'Kara-Honey',artist: 'KarA',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/Kara-Honey.mp3',duration: 300},
{id: 12,title: 'kiss-因为是女子',artist: 'kiss',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/kiss-因为是女子.mp3',duration: 300},
{id: 13,title: 'Lyn-爱情都是谎言',artist: 'Lyn',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/Lyn-爱情都是谎言.mp3',duration: 300},
{id: 14,title: 'Lyn-歌信',artist: 'Lyn',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/Lyn-歌信.mp3',duration: 300},
{id: 15,title: 'Psy-江南Style',artist: 'Psy',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/Psy-江南Style.mp3',duration: 300},
{id: 16,title: 'rania-DrFeelGood',artist: 'raniA',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/rania-DrFeelGood.mp3',duration: 300},
{id: 17,title: 'sHarp-我的嘴唇如暖暖的咖啡',artist: 'sHarp',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/sHarp-我的嘴唇如暖暖的咖啡.mp3',duration: 300},
{id: 18,title: 'tara-LoveyDovey',artist: 'tarA',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/tara-LoveyDovey.mp3',duration: 300},
{id: 19,title: 'WAX',artist: 'WAX',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/WAX.mp3',duration: 300},
{id: 20,title: 'WAX-Money',artist: 'WAX',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/WAX-Money.mp3',duration: 300},
{id: 21,title: 'WAX-改变化装',artist: 'WAX',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/WAX-改变化装.mp3',duration: 300},
{id: 22,title: 'WAX-渴望爱情',artist: 'WAX',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/WAX-渴望爱情.mp3',duration: 300},
{id: 23,title: 'WAX-一通电话也不行',artist: 'WAX',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/WAX-一通电话也不行.mp3',duration: 300},
{id: 24,title: 'WAX-余情',artist: 'WAX',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/WAX-余情.mp3',duration: 300},
{id: 25,title: 'WAX-只有眼泪只有眼泪',artist: 'WAX',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/WAX-只有眼泪只有眼泪.mp3',duration: 300},
{id: 26,title: 'WAX-坐着地铁',artist: 'WAX',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/WAX-坐着地铁.mp3',duration: 300},
{id: 27,title: 'WonderGirls-nobody',artist: 'WonderGirls',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/WonderGirls-nobody.mp3',duration: 300},
{id: 28,title: '冬季恋歌-从开始到现在',artist: '冬季恋歌',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/冬季恋歌-从开始到现在.mp3',duration: 300},
{id: 68,title: '洪真英-活着',artist: '洪真英',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/洪真英-活着.mp3',duration: 300},
{id: 29,title: '蓝色生死恋-祈祷',artist: '蓝色生死恋',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/蓝色生死恋-祈祷.mp3',duration: 300},
{id: 30,title: '李孝利-10minutes',artist: '李孝利',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/李孝利-10minutes.mp3',duration: 300},
{id: 31,title: '李秀英-AlsoILoveYou',artist: '李秀英',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/李秀英-AlsoILoveYou.mp3',duration: 300},
{id: 32,title: '李秀英-NEVERAGAIN',artist: '李秀英',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/李秀英-NEVERAGAIN.mp3',duration: 300},
{id: 33,title: '李秀英-我们',artist: '李秀英',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/李秀英-我们.mp3',duration: 300},
{id: 34,title: '李贞贤-独一无二',artist: '李贞贤',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/李贞贤-独一无二.mp3',duration: 300},
{id: 35,title: '李贞贤-眉飞色舞',artist: '李贞贤',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/李贞贤-眉飞色舞.mp3',duration: 300},
{id: 36,title: '李贞贤-月亮啊月亮',artist: '李贞贤',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/李贞贤-月亮啊月亮.mp3',duration: 300},
{id: 37,title: '柳真-ChaChA',artist: '柳真',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/柳真-ChaCha.mp3',duration: 300},
{id: 38,title: '裴勇俊-MyMemory',artist: '裴勇俊',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/裴勇俊-MyMemory.mp3',duration: 300},
{id: 39,title: '朴惠京-RAIN',artist: '朴惠京',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/朴惠京-RAIN.mp3',duration: 300},
{id: 40,title: '朴慧京-yesterday',artist: '朴慧京',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/朴慧京-yesterday.mp3',duration: 300},
{id: 41,title: '朴慧京-结婚',artist: '朴慧京',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/朴慧京-结婚.mp3',duration: 300},
{id: 42,title: '朴孝信-雪之花',artist: '朴孝信',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/朴孝信-雪之花.mp3',duration: 300},
{id: 43,title: '少女时代-Animal',artist: '少女时代',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-Animal.mp3',duration: 300},
{id: 44,title: '少女时代-BeepBeep',artist: '少女时代',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-BeepBeep.mp3',duration: 300},
{id: 45,title: '少女时代-GalaxySupernovA',artist: '少女时代',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-GalaxySupernova.mp3',duration: 300},
{id: 47,title: '少女时代-Gee',artist: '少女时代',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-Gee.mp3',duration: 300},
{id: 46,title: '少女时代-Gee(Japanesever.)',artist: '少女时代',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-Gee(Japanesever.).mp3',duration: 300},
{id: 48,title: '少女时代-Holiday',artist: '少女时代',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-Holiday.mp3',duration: 300},
{id: 49,title: '少女时代-HOOT',artist: '少女时代',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-HOOT.mp3',duration: 300},
{id: 50,title: '少女时代-IntoTheNewWorld',artist: '少女时代',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-IntoTheNewWorld.mp3',duration: 300},
{id: 51,title: '少女时代-Mr.Mr.(Japanesever.)',artist: '少女时代',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-Mr.Mr.(Japanesever.).mp3',duration: 300},
{id: 52,title: '少女时代-MrTaxi',artist: '少女时代',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-MrTaxi.mp3',duration: 300},
{id: 54,title: '少女时代-Oh!',artist: '少女时代',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-Oh!.mp3',duration: 300},
{id: 53,title: '少女时代-Oh!(Japanesever.)',artist: '少女时代',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-Oh!(Japanesever.).mp3',duration: 300},
{id: 55,title: '少女时代-Paparazzi',artist: '少女时代',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-Paparazzi.mp3',duration: 300},
{id: 56,title: '少女时代-PARTY',artist: '少女时代',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-PARTY.mp3',duration: 300},
{id: 57,title: '少女时代-RunDevilRun',artist: '少女时代',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-RunDevilRun.mp3',duration: 300},
{id: 58,title: '少女时代-TheBoys',artist: '少女时代',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-TheBoys.mp3',duration: 300},
{id: 59,title: '申彗星-LoveLetter',artist: '申彗星',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/申彗星-LoveLetter.mp3',duration: 300},
{id: 60,title: '申彗星-爱情病',artist: '申彗星',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/申彗星-爱情病.mp3',duration: 300},
{id: 61,title: '申彗星-我慢慢死去',artist: '申彗星',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/申彗星-我慢慢死去.mp3',duration: 300},
{id: 62,title: '申彗星-在那个位置',artist: '申彗星',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/申彗星-在那个位置.mp3',duration: 300},
{id: 63,title: '淑熙-啦啦啦',artist: '淑熙',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/淑熙-啦啦啦.mp3',duration: 300},
{id: 64,title: '孙丹菲-星期六晚上',artist: '孙丹菲',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/孙丹菲-星期六晚上.mp3',duration: 300},
{id: 65,title: '我的野蛮女友-我相信',artist: '我的野蛮女友',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/我的野蛮女友-我相信.mp3',duration: 300},
{id: 66,title: '严正花-都走吧',artist: '严正花',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/严正花-都走吧.mp3',duration: 300},
{id: 67,title: '玉珠铉-仲夏夜之梦',artist: '玉珠铉',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/玉珠铉-仲夏夜之梦.mp3',duration: 300}
];

// 如果需要在其他环境中使用，也可导出
// 浏览器环境中直接使用全局变量 MUSIC_DATA
if (typeof module !== 'undefined' && module.exports) {
  module.exports = MUSIC_DATA;
}