// ============================================================
//  music.js  —  音乐播放列表数据
//  请将此文件与 index.html 放在同一目录下
// ============================================================

const PURE_DATA = [
{id: 1,title: 'Chunyy-爱在四月雪',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-爱在四月雪.mp3',duration: 300},
{id: 2,title: 'Chunyy-安魂曲',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-安魂曲.mp3',duration: 300},
{id: 3,title: 'Chunyy-安妮的歌',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-安妮的歌.mp3',duration: 300},
{id: 4,title: 'Chunyy-宝贝珍之歌',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-宝贝珍之歌.mp3',duration: 300},
{id: 5,title: 'Chunyy-沉睡的森林',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-沉睡的森林.mp3',duration: 300},
{id: 6,title: 'Chunyy-沉思曲',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-沉思曲.mp3',duration: 300},
{id: 7,title: 'Chunyy-初恋的地方',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-初恋的地方.mp3',duration: 300},
{id: 8,title: 'Chunyy-春之声圆舞曲 古典钢琴',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-春之声圆舞曲 古典钢琴.mp3',duration: 300},
{id: 9,title: 'Chunyy-大溪地清流 米奴哀舞',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-大溪地清流 米奴哀舞.mp3',duration: 300},
{id: 10,title: 'Chunyy-第六感生死恋',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-第六感生死恋.mp3',duration: 300},
{id: 11,title: 'Chunyy-断情殇',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-断情殇.mp3',duration: 300},
{id: 12,title: 'Chunyy-飞鼠溪',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-飞鼠溪.mp3',duration: 300},
{id: 13,title: 'Chunyy-风的气息',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-风的气息.mp3',duration: 300},
{id: 14,title: 'Chunyy-风中之尘',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-风中之尘.mp3',duration: 300},
{id: 15,title: 'Chunyy-格里格索尔维格之歌',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-格里格索尔维格之歌.mp3',duration: 300},
{id: 16,title: 'Chunyy-和兰花在一起',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-和兰花在一起.mp3',duration: 300},
{id: 17,title: 'Chunyy-很好听',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-很好听.mp3',duration: 300},
{id: 18,title: 'Chunyy-火宵之月',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-火宵之月.mp3',duration: 300},
{id: 19,title: 'Chunyy-卡布里的月光',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-卡布里的月光.mp3',duration: 300},
{id: 20,title: 'Chunyy-卡农钢琴曲',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-卡农钢琴曲.mp3',duration: 300},
{id: 21,title: 'Chunyy-蓝色的爱',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-蓝色的爱.mp3',duration: 300},
{id: 22,title: 'Chunyy-梁祝之化蝶 笛子',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-梁祝之化蝶 笛子.mp3',duration: 300},
{id: 23,title: 'Chunyy-绵雪',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-绵雪.mp3',duration: 300},
{id: 24,title: 'Chunyy-茉莉花',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-茉莉花.mp3',duration: 300},
{id: 25,title: 'Chunyy-森林中的一天',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-森林中的一天.mp3',duration: 300},
{id: 26,title: 'Chunyy-似曾相识',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-似曾相识.mp3',duration: 300},
{id: 27,title: 'Chunyy-守护你的天使',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-守护你的天使.mp3',duration: 300},
{id: 28,title: 'Chunyy-树蛙之歌',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-树蛙之歌.mp3',duration: 300},
{id: 29,title: 'Chunyy-水之轮回',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-水之轮回.mp3',duration: 300},
{id: 30,title: 'Chunyy-天鹅湖',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-天鹅湖.mp3',duration: 300},
{id: 31,title: 'Chunyy-万福玛丽亚',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-万福玛丽亚.mp3',duration: 300},
{id: 32,title: 'Chunyy-我的海洋',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-我的海洋.mp3',duration: 300},
{id: 33,title: 'Chunyy-西班牙斗牛士进行曲',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-西班牙斗牛士进行曲.mp3',duration: 300},
{id: 34,title: 'Chunyy-西藏的月',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-西藏的月.mp3',duration: 300},
{id: 35,title: 'Chunyy-昔日情怀',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-昔日情怀.mp3',duration: 300},
{id: 36,title: 'Chunyy-夏日华尔兹',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-夏日华尔兹.mp3',duration: 300},
{id: 37,title: 'Chunyy-乡间晚风',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-乡间晚风.mp3',duration: 300},
{id: 38,title: 'Chunyy-相识也是缘份',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-相识也是缘份.mp3',duration: 300},
{id: 39,title: 'Chunyy-小步舞曲',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-小步舞曲.mp3',duration: 300},
{id: 40,title: 'Chunyy-小雨落在你脸上',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-小雨落在你脸上.mp3',duration: 300},
{id: 41,title: 'Chunyy-雪之梦',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-雪之梦.mp3',duration: 300},
{id: 42,title: 'Chunyy-野鸟情歌',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-野鸟情歌.mp3',duration: 300},
{id: 43,title: 'Chunyy-印象之旅',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-印象之旅.mp3',duration: 300},
{id: 44,title: 'Chunyy-雨林深处',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-雨林深处.mp3',duration: 300},
{id: 45,title: 'Chunyy-雨中漫步',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-雨中漫步.mp3',duration: 300},
{id: 46,title: 'Chunyy-月光下的凤尾竹',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-月光下的凤尾竹.mp3',duration: 300},
{id: 47,title: 'Chunyy-云淡风轻',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-云淡风轻.mp3',duration: 300},
{id: 48,title: 'Chunyy-只此一生',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-只此一生.mp3',duration: 300},
{id: 49,title: 'Chunyy-最终幻想',artist: '纯音乐',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-最终幻想.mp3',duration: 300},
{id: 50,title: 'Joanie madden-The level plain',artist: 'Joanie madden',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Joanie madden-The level plain.mp3',duration: 300},
{id: 51,title: 'yiruma-雨的印记',artist: 'yirumA',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/yiruma-雨的印记.mp3',duration: 300},
{id: 52,title: '爱尔兰风笛 漫步神秘园',artist: '爱尔兰风笛',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/爱尔兰风笛 漫步神秘园.mp3',duration: 300},
{id: 53,title: '爱尔兰口哨女皇madden-爱尔兰画眉',artist: '爱尔兰口哨女皇madden',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/爱尔兰口哨女皇madden-爱尔兰画眉.mp3',duration: 300},
{id: 54,title: '班得瑞-chariots of fire',artist: '班得瑞',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-chariots of fire.mp3',duration: 300},
{id: 55,title: '班得瑞-diamonds',artist: '班得瑞',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-diamonds.mp3',duration: 300},
{id: 56,title: '班得瑞-EI condor pasA',artist: '班得瑞',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-EI condor pasa.mp3',duration: 300},
{id: 57,title: '班得瑞-i want to know love is',artist: '班得瑞',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-i want to know love is.mp3',duration: 300},
{id: 58,title: '班得瑞-i_swear',artist: '班得瑞',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-i_swear.mp3',duration: 300},
{id: 59,title: '班得瑞-imagine',artist: '班得瑞',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-imagine.mp3',duration: 300},
{id: 60,title: '班得瑞-into red velvet',artist: '班得瑞',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-into red velvet.mp3',duration: 300},
{id: 61,title: '班得瑞-moment of fantasy',artist: '班得瑞',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-moment of fantasy.mp3',duration: 300},
{id: 62,title: '班得瑞-one moment in time',artist: '班得瑞',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-one moment in time.mp3',duration: 300},
{id: 63,title: '班得瑞-tenderness',artist: '班得瑞',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-tenderness.mp3',duration: 300},
{id: 64,title: '班得瑞-the sounds of silence',artist: '班得瑞',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-the sounds of silence.mp3',duration: 300},
{id: 65,title: '班得瑞-tims lullaby',artist: '班得瑞',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-tims lullaby.mp3',duration: 300},
{id: 66,title: '班得瑞-安妮的仙境',artist: '班得瑞',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-安妮的仙境.mp3',duration: 300},
{id: 67,title: '班得瑞-变幻之风',artist: '班得瑞',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-变幻之风.mp3',duration: 300},
{id: 68,title: '班得瑞-晨光',artist: '班得瑞',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-晨光.mp3',duration: 300},
{id: 69,title: '班得瑞-初雪',artist: '班得瑞',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-初雪.mp3',duration: 300},
{id: 70,title: '班得瑞-春水',artist: '班得瑞',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-春水.mp3',duration: 300},
{id: 71,title: '班得瑞-春野',artist: '班得瑞',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-春野.mp3',duration: 300},
{id: 72,title: '班得瑞-非洲日落',artist: '班得瑞',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-非洲日落.mp3',duration: 300},
{id: 73,title: '班得瑞-风的呢喃',artist: '班得瑞',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-风的呢喃.mp3',duration: 300},
{id: 74,title: '班得瑞-海王星',artist: '班得瑞',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-海王星.mp3',duration: 300},
{id: 75,title: '班得瑞-火战车',artist: '班得瑞',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-火战车.mp3',duration: 300},
{id: 76,title: '班得瑞-涟漪',artist: '班得瑞',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-涟漪.mp3',duration: 300},
{id: 77,title: '班得瑞-马可波罗',artist: '班得瑞',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-马可波罗.mp3',duration: 300},
{id: 78,title: '班得瑞-满天星',artist: '班得瑞',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-满天星.mp3',duration: 300},
{id: 79,title: '班得瑞-秘密',artist: '班得瑞',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-秘密.mp3',duration: 300},
{id: 80,title: '班得瑞-排箫 老鹰之歌',artist: '班得瑞',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-排箫 老鹰之歌.mp3',duration: 300},
{id: 81,title: '班得瑞-清晨',artist: '班得瑞',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-清晨.mp3',duration: 300},
{id: 82,title: '班得瑞-日光海岸',artist: '班得瑞',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-日光海岸.mp3',duration: 300},
{id: 83,title: '班得瑞-天堂之门',artist: '班得瑞',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-天堂之门.mp3',duration: 300},
{id: 84,title: '班得瑞-微风山谷',artist: '班得瑞',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-微风山谷.mp3',duration: 300},
{id: 85,title: '班得瑞-无止境的见识',artist: '班得瑞',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-无止境的见识.mp3',duration: 300},
{id: 86,title: '班得瑞-夏日华尔兹',artist: '班得瑞',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-夏日华尔兹.mp3',duration: 300},
{id: 87,title: '班得瑞-仙境',artist: '班得瑞',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-仙境.mp3',duration: 300},
{id: 88,title: '班得瑞-依卡路斯的羽翼',artist: '班得瑞',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-依卡路斯的羽翼.mp3',duration: 300},
{id: 89,title: '班得瑞-忧郁的爱',artist: '班得瑞',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-忧郁的爱.mp3',duration: 300},
{id: 90,title: '班得瑞-月光',artist: '班得瑞',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-月光.mp3',duration: 300},
{id: 91,title: '班得瑞-追梦人',artist: '班得瑞',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-追梦人.mp3',duration: 300},
{id: 92,title: '班得瑞-紫蝴蝶',artist: '班得瑞',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-紫蝴蝶.mp3',duration: 300},
{id: 93,title: '班德瑞-巴格达的星星',artist: '班德瑞',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班德瑞-巴格达的星星.mp3',duration: 300},
{id: 94,title: '贝多芬-悲怆奏鸣曲',artist: '贝多芬',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/贝多芬-悲怆奏鸣曲.mp3',duration: 300},
{id: 95,title: '贝多芬-命运交响乐',artist: '贝多芬',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/贝多芬-命运交响乐.mp3',duration: 300},
{id: 96,title: '贝多芬-田园交响曲',artist: '贝多芬',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/贝多芬-田园交响曲.mp3',duration: 300},
{id: 97,title: '贝多芬-月光奏鸣曲',artist: '贝多芬',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/贝多芬-月光奏鸣曲.mp3',duration: 300},
{id: 98,title: '杜普雷-殇',artist: '杜普雷',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/杜普雷-殇.mp3',duration: 300},
{id: 99,title: '宫崎骏 龙猫-水晶音乐',artist: '宫崎骏',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/宫崎骏 龙猫-水晶音乐.mp3',duration: 300},
{id: 100,title: '久石让-天空之城',artist: '久石让',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/久石让-天空之城.mp3',duration: 300},
{id: 101,title: '凯文柯恩-走过绿意',artist: '凯文柯恩',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/凯文柯恩-走过绿意.mp3',duration: 300},
{id: 102,title: '浪客剑心-In Memories “A boy meets The Man”',artist: '浪客剑心',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/浪客剑心-In Memories “A boy meets The Man”.mp3',duration: 300},
{id: 103,title: '李斯特-钟',artist: '李斯特',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/李斯特-钟.mp3',duration: 300},
{id: 104,title: '理查德 克莱德曼-爱的纪念',artist: '理查德 克莱德曼',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-爱的纪念.mp3',duration: 300},
{id: 105,title: '理查德 克莱德曼-爱的协奏曲',artist: '理查德 克莱德曼',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-爱的协奏曲.mp3',duration: 300},
{id: 106,title: '理查德 克莱德曼-爱之梦',artist: '理查德 克莱德曼',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-爱之梦.mp3',duration: 300},
{id: 107,title: '理查德 克莱德曼-出埃及记',artist: '理查德 克莱德曼',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-出埃及记.mp3',duration: 300},
{id: 108,title: '理查德 克莱德曼-给母亲的信',artist: '理查德 克莱德曼',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-给母亲的信.mp3',duration: 300},
{id: 109,title: '理查德 克莱德曼-海边的祈祷',artist: '理查德 克莱德曼',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-海边的祈祷.mp3',duration: 300},
{id: 110,title: '理查德 克莱德曼-海边的星空',artist: '理查德 克莱德曼',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-海边的星空.mp3',duration: 300},
{id: 111,title: '理查德 克莱德曼-欢乐颂',artist: '理查德 克莱德曼',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-欢乐颂.mp3',duration: 300},
{id: 112,title: '理查德 克莱德曼-欢乐之歌',artist: '理查德 克莱德曼',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-欢乐之歌.mp3',duration: 300},
{id: 113,title: '理查德 克莱德曼-蓝色的爱',artist: '理查德 克莱德曼',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-蓝色的爱.mp3',duration: 300},
{id: 114,title: '理查德 克莱德曼-蓝色狂想曲',artist: '理查德 克莱德曼',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-蓝色狂想曲.mp3',duration: 300},
{id: 115,title: '理查德 克莱德曼-罗密欧与朱丽叶',artist: '理查德 克莱德曼',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-罗密欧与朱丽叶.mp3',duration: 300},
{id: 116,title: '理查德 克莱德曼-玫瑰色的人生',artist: '理查德 克莱德曼',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-玫瑰色的人生.mp3',duration: 300},
{id: 117,title: '理查德 克莱德曼-梦中的婚礼',artist: '理查德 克莱德曼',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-梦中的婚礼.mp3',duration: 300},
{id: 118,title: '理查德 克莱德曼-梦中的鸟',artist: '理查德 克莱德曼',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-梦中的鸟.mp3',duration: 300},
{id: 119,title: '理查德 克莱德曼-秘密的庭院',artist: '理查德 克莱德曼',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-秘密的庭院.mp3',duration: 300},
{id: 120,title: '理查德 克莱德曼-乒乓之恋',artist: '理查德 克莱德曼',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-乒乓之恋.mp3',duration: 300},
{id: 121,title: '理查德 克莱德曼-秋日私语',artist: '理查德 克莱德曼',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-秋日私语.mp3',duration: 300},
{id: 122,title: '理查德 克莱德曼-柔如彩虹',artist: '理查德 克莱德曼',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-柔如彩虹.mp3',duration: 300},
{id: 123,title: '理查德 克莱德曼-伤感乐曲',artist: '理查德 克莱德曼',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-伤感乐曲.mp3',duration: 300},
{id: 124,title: '理查德 克莱德曼-少女的祈祷',artist: '理查德 克莱德曼',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-少女的祈祷.mp3',duration: 300},
{id: 125,title: '理查德 克莱德曼-水边的阿狄丽娜',artist: '理查德 克莱德曼',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-水边的阿狄丽娜.mp3',duration: 300},
{id: 126,title: '理查德 克莱德曼-思乡曲',artist: '理查德 克莱德曼',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-思乡曲.mp3',duration: 300},
{id: 127,title: '理查德 克莱德曼-瓦妮莎的微笑',artist: '理查德 克莱德曼',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-瓦妮莎的微笑.mp3',duration: 300},
{id: 128,title: '理查德 克莱德曼-忘却的悲伤',artist: '理查德 克莱德曼',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-忘却的悲伤.mp3',duration: 300},
{id: 129,title: '理查德 克莱德曼-威尼斯之旅',artist: '理查德 克莱德曼',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-威尼斯之旅.mp3',duration: 300},
{id: 130,title: '理查德 克莱德曼-午后的旅行',artist: '理查德 克莱德曼',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-午后的旅行.mp3',duration: 300},
{id: 131,title: '理查德 克莱德曼-星空',artist: '理查德 克莱德曼',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-星空.mp3',duration: 300},
{id: 132,title: '理查德 克莱德曼-野花',artist: '理查德 克莱德曼',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-野花.mp3',duration: 300},
{id: 133,title: '理查德 克莱德曼-英雄交响曲',artist: '理查德 克莱德曼',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-英雄交响曲.mp3',duration: 300},
{id: 134,title: '理查德 克莱德曼-永远爱你',artist: '理查德 克莱德曼',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-永远爱你.mp3',duration: 300},
{id: 135,title: '理查德 克莱德曼-致爱丽丝',artist: '理查德 克莱德曼',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-致爱丽丝.mp3',duration: 300},
{id: 136,title: '绿钢琴 乐曲',artist: '绿钢琴 乐曲',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/绿钢琴 乐曲.mp3',duration: 300},
{id: 137,title: '马克西姆-克罗地亚狂想曲',artist: '马克西姆',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/马克西姆-克罗地亚狂想曲.mp3',duration: 300},
{id: 138,title: '马友友-天鹅 大提琴演奏',artist: '马友友',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/马友友-天鹅 大提琴演奏.mp3',duration: 300},
{id: 139,title: '莫扎特 c大调小星星变奏曲',artist: '莫扎特',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/莫扎特 c大调小星星变奏曲.mp3',duration: 300},
{id: 140,title: '莫扎特-安魂曲',artist: '莫扎特',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/莫扎特-安魂曲.mp3',duration: 300},
{id: 141,title: '莫扎特-魔笛',artist: '莫扎特',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/莫扎特-魔笛.mp3',duration: 300},
{id: 142,title: '莫扎特-土耳其进行曲',artist: '莫扎特',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/莫扎特-土耳其进行曲.mp3',duration: 300},
{id: 143,title: '莫扎特-小步舞曲',artist: '莫扎特',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/莫扎特-小步舞曲.mp3',duration: 300},
{id: 144,title: '莫扎特-摇篮曲',artist: '莫扎特',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/莫扎特-摇篮曲.mp3',duration: 300},
{id: 145,title: '莫扎特-幽默曲',artist: '莫扎特',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/莫扎特-幽默曲.mp3',duration: 300},
{id: 146,title: '齐普利安·波隆贝斯库-永恒的记忆',artist: '齐普利安·波隆贝斯库',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/齐普利安·波隆贝斯库-永恒的记忆.mp3',duration: 300},
{id: 147,title: '犬夜叉-哀歌',artist: '犬夜叉',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/犬夜叉-哀歌.mp3',duration: 300},
{id: 148,title: '犬夜叉-跨越时代的思念',artist: '犬夜叉',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/犬夜叉-跨越时代的思念.mp3',duration: 300},
{id: 149,title: '神秘园-莲花',artist: '神秘园',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/神秘园-莲花.mp3',duration: 300},
{id: 150,title: '神秘园-夜曲',artist: '神秘园',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/神秘园-夜曲.mp3',duration: 300},
{id: 151,title: '神秘园-月亮门',artist: '神秘园',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/神秘园-月亮门.mp3',duration: 300},
{id: 152,title: '神秘园之歌-月亮门',artist: '神秘园之歌',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/神秘园之歌-月亮门.mp3',duration: 300},
{id: 153,title: '神思者-Project',artist: '神思者',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/神思者-Project.mp3',duration: 300},
{id: 154,title: '神思者-悲情城市',artist: '神思者',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/神思者-悲情城市.mp3',duration: 300},
{id: 155,title: '神思者-故宫的记忆',artist: '神思者',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/神思者-故宫的记忆.mp3',duration: 300},
{id: 156,title: '神思者-海之女神',artist: '神思者',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/神思者-海之女神.mp3',duration: 300},
{id: 157,title: '舒伯特-圣母颂',artist: '舒伯特',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/舒伯特-圣母颂.mp3',duration: 300},
{id: 158,title: '舒曼-梦幻曲',artist: '舒曼',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/舒曼-梦幻曲.mp3',duration: 300},
{id: 159,title: '威尔第 茶花女-普罗旺斯的陆地和海洋',artist: '威尔第',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/威尔第 茶花女-普罗旺斯的陆地和海洋.mp3',duration: 300},
{id: 160,title: '乌鸦 片尾曲-月光石 RurutiA',artist: '乌鸦 片尾曲',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/乌鸦 片尾曲-月光石 Rurutia.mp3',duration: 300},
{id: 161,title: '喜多郎-飞天',artist: '喜多郎',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/喜多郎-飞天.mp3',duration: 300},
{id: 162,title: '喜多郎-菩提树',artist: '喜多郎',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/喜多郎-菩提树.mp3',duration: 300},
{id: 163,title: '萧邦-幻想即兴曲',artist: '萧邦',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/萧邦-幻想即兴曲.mp3',duration: 300},
{id: 164,title: '徐仁修-森林狂想曲',artist: '徐仁修',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/徐仁修-森林狂想曲.mp3',duration: 300},
{id: 165,title: '姚斯婷-寂静之声',artist: '姚斯婷',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/姚斯婷-寂静之声.mp3',duration: 300},
{id: 166,title: '约翰 施特劳斯-溜冰圆舞曲',artist: '约翰 施特劳斯',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/约翰 施特劳斯-溜冰圆舞曲.mp3',duration: 300},
{id: 167,title: '约翰 施特劳斯-闲聊波尔卡',artist: '约翰 施特劳斯',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/约翰 施特劳斯-闲聊波尔卡.mp3',duration: 300},
{id: 168,title: '约翰·施特劳斯-蓝色多瑙河',artist: '约翰·施特劳斯',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/约翰·施特劳斯-蓝色多瑙河.mp3',duration: 300},
{id: 169,title: '约翰·施特劳斯-维也纳森林的故事',artist: '约翰·施特劳斯',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/约翰·施特劳斯-维也纳森林的故事.mp3',duration: 300},
{id: 170,title: '约纳森-杜鹃圆舞曲',artist: '约纳森',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/约纳森-杜鹃圆舞曲.mp3',duration: 300},
{id: 171,title: '宗次郎-故乡的原风景',artist: '宗次郎',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/宗次郎-故乡的原风景.mp3',duration: 300}
];

// 如果需要在其他环境中使用，也可导出
// 浏览器环境中直接使用全局变量 MUSIC_DATA
if (typeof module !== 'undefined' && module.exports) {
  module.exports = MUSIC_DATA;
}