// ============================================================
//  music.js  —  音乐播放列表数据
//  请将此文件与 index.html 放在同一目录下
// ============================================================

const USA_DATA = [
{id: 1,title: 'Adaro-Es Ist Ein Schnee Gefallen',artist: 'Adaro',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Adaro-Es Ist Ein Schnee Gefallen.mp3',duration: 300},
{id: 2,title: 'Adele-Hello',artist: 'Adele',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Adele-Hello.mp3',duration: 300},
{id: 3,title: 'Adele-Rolling in the Deep',artist: 'Adele',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Adele-Rolling in the Deep.mp3',duration: 300},
{id: 4,title: 'Air Supply-Making Love Out Of Nothing At All',artist: 'Air Supply',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Air Supply-Making Love Out Of Nothing At All.mp3',duration: 300},
{id: 5,title: 'Alan Walker-Alone',artist: 'Alan Walker',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Alan Walker-Alone.mp3',duration: 300},
{id: 6,title: 'Alan Walker-Faded',artist: 'Alan Walker',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Alan Walker-Faded.mp3',duration: 300},
{id: 7,title: 'Alan Walker-The Spectre',artist: 'Alan Walker',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Alan Walker-The Spectre.mp3',duration: 300},
{id: 8,title: 'AmyDiamond-Heartbeats',artist: 'AmyDiamond',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/AmyDiamond-Heartbeats.mp3',duration: 300},
{id: 9,title: 'Ann Winsborn-La La Love On My Mind',artist: 'Ann Winsborn',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Ann Winsborn-La La Love On My Mind.mp3',duration: 300},
{id: 10,title: 'Aoi Teshima-the rose',artist: 'Aoi TeshimA',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Aoi Teshima-the rose.mp3',duration: 300},
{id: 11,title: 'Aqua-My Oh My',artist: 'AquA',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Aqua-My Oh My.mp3',duration: 300},
{id: 12,title: 'Ava Max-Salt',artist: 'Ava Max',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Ava Max-Salt.mp3',duration: 300},
{id: 13,title: 'Ava Max-Sweet but Psycho',artist: 'Ava Max',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Ava Max-Sweet but Psycho.mp3',duration: 300},
{id: 14,title: 'AvrilLavigne-IamWithYou',artist: 'AvrilLavigne',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/AvrilLavigne-IamWithYou.mp3',duration: 300},
{id: 15,title: 'Backstreet Boys-As Long As You Love Me',artist: 'Backstreet Boys',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Backstreet Boys-As Long As You Love Me.mp3',duration: 300},
{id: 16,title: 'Backstreet Boys-Everybody',artist: 'Backstreet Boys',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Backstreet Boys-Everybody.mp3',duration: 300},
{id: 17,title: 'Backstreet Boys-I want it that way',artist: 'Backstreet Boys',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Backstreet Boys-I want it that way.mp3',duration: 300},
{id: 18,title: 'Backstreet Boys-Larger Than Life',artist: 'Backstreet Boys',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Backstreet Boys-Larger Than Life.mp3',duration: 300},
{id: 19,title: 'Bertie Higgins-CasablancA',artist: 'Bertie Higgins',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Bertie Higgins-Casablanca.mp3',duration: 300},
{id: 20,title: 'Blue-All Rise',artist: 'Blue',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Blue-All Rise.mp3',duration: 300},
{id: 21,title: 'Blue-One Love',artist: 'Blue',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Blue-One Love.mp3',duration: 300},
{id: 22,title: 'Bon Jovi-Its My Life',artist: 'Bon Jovi',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Bon Jovi-Its My Life.mp3',duration: 300},
{id: 23,title: 'Britney Spears-BabyOneMoreTime',artist: 'Britney Spears',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Britney Spears-BabyOneMoreTime.mp3',duration: 300},
{id: 24,title: 'Britney Spears-everytime',artist: 'Britney Spears',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Britney Spears-everytime.mp3',duration: 300},
{id: 25,title: 'BwO-Sunshine In The Rain',artist: 'BwO',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/BwO-Sunshine In The Rain.mp3',duration: 300},
{id: 26,title: 'CaraDillon-Craigie Hill',artist: 'CaraDillon',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/CaraDillon-Craigie Hill.mp3',duration: 300},
{id: 27,title: 'Carlow-for seA',artist: 'Carlow',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Carlow-for sea.mp3',duration: 300},
{id: 28,title: 'Carlow-If love has divine will',artist: 'Carlow',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Carlow-If love has divine will.mp3',duration: 300},
{id: 29,title: 'Carpenters-Yesterday Once More',artist: 'Carpenters',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Carpenters-Yesterday Once More.mp3',duration: 300},
{id: 30,title: 'Celine Dion-All By Myself',artist: 'Celine Dion',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Celine Dion-All By Myself.mp3',duration: 300},
{id: 31,title: 'Celine Dion-Because You Loved Me',artist: 'Celine Dion',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Celine Dion-Because You Loved Me.mp3',duration: 300},
{id: 32,title: 'Celine Dion-I Surrender',artist: 'Celine Dion',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Celine Dion-I Surrender.mp3',duration: 300},
{id: 33,title: 'Celine Dion-My Heart Will Go On',artist: 'Celine Dion',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Celine Dion-My Heart Will Go On.mp3',duration: 300},
{id: 34,title: 'Celine Dion-Thats the Way It Is',artist: 'Celine Dion',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Celine Dion-Thats the Way It Is.mp3',duration: 300},
{id: 35,title: 'Celine Dion-The Power Of Love',artist: 'Celine Dion',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Celine Dion-The Power Of Love.mp3',duration: 300},
{id: 36,title: 'Charlie Puth、Selena Gomez-We Dont Talk Anymore',artist: 'Charlie Puth、Selena Gomez',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Charlie Puth、Selena Gomez-We Dont Talk Anymore.mp3',duration: 300},
{id: 37,title: 'CHROMANCE-Wrap Me In Plastic',artist: 'CHROMANCE',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/CHROMANCE-Wrap Me In Plastic.mp3',duration: 300},
{id: 38,title: 'Coldplay-Yellow',artist: 'Coldplay',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Coldplay-Yellow.mp3',duration: 300},
{id: 39,title: 'Dan Fogelberg-Sutters Mill',artist: 'Dan Fogelberg',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Dan Fogelberg-Sutters Mill.mp3',duration: 300},
{id: 40,title: 'Dana Winner-Moonlight Shadow',artist: 'Dana Winner',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Dana Winner-Moonlight Shadow.mp3',duration: 300},
{id: 41,title: 'Dana Winner-Woman in Love',artist: 'Dana Winner',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Dana Winner-Woman in Love.mp3',duration: 300},
{id: 42,title: 'Daniel Powter-Free Loop',artist: 'Daniel Powter',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Daniel Powter-Free Loop.mp3',duration: 300},
{id: 43,title: 'Darin-Be What You Wanna Be',artist: 'Darin',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Darin-Be What You Wanna Be.mp3',duration: 300},
{id: 44,title: 'Delacey-Dream It Possible',artist: 'Delacey',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Delacey-Dream It Possible.mp3',duration: 300},
{id: 45,title: 'DemiLovato-LetItGo',artist: 'DemiLovato',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/DemiLovato-LetItGo.mp3',duration: 300},
{id: 46,title: 'Djokawari-luv letter',artist: 'Djokawari',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Djokawari-luv letter.mp3',duration: 300},
{id: 47,title: 'Eagles-Hotel CaliforniA',artist: 'Eagles',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Eagles-Hotel California.mp3',duration: 300},
{id: 48,title: 'EdSheeran-Shape Of You',artist: 'EdSheeran',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/EdSheeran-Shape Of You.mp3',duration: 300},
{id: 49,title: 'Emilia-big big world',artist: 'EmiliA',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Emilia-big big world.mp3',duration: 300},
{id: 50,title: 'Eminem、Rihanna-Love The Way You Lie',artist: 'Eminem、RihannA',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Eminem、Rihanna-Love The Way You Lie.mp3',duration: 300},
{id: 51,title: 'Enya-May It Be',artist: 'EnyA',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Enya-May It Be.mp3',duration: 300},
{id: 52,title: 'Enya-Only Time',artist: 'EnyA',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Enya-Only Time.mp3',duration: 300},
{id: 53,title: 'Era-The Mass',artist: 'ErA',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Era-The Mass.mp3',duration: 300},
{id: 54,title: 'Gabriel MarianI-ts My Life',artist: 'Gabriel MarianI',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Gabriel MarianI-ts My Life.mp3',duration: 300},
{id: 55,title: 'Gareth Gates-Anyone of Us',artist: 'Gareth Gates',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Gareth Gates-Anyone of Us.mp3',duration: 300},
{id: 56,title: 'George Benson-Nothings Gonna Change My Love For You',artist: 'George Benson',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/George Benson-Nothings Gonna Change My Love For You.mp3',duration: 300},
{id: 57,title: 'George Michael-Careless Whisper',artist: 'George Michael',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/George Michael-Careless Whisper.mp3',duration: 300},
{id: 58,title: 'Grant Miller-Colder Than Ice',artist: 'Grant Miller',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Grant Miller-Colder Than Ice.mp3',duration: 300},
{id: 59,title: 'Groove Coverage-Far Away From Home',artist: 'Groove Coverage',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Groove Coverage-Far Away From Home.mp3',duration: 300},
{id: 60,title: 'Groove Coverage-God Is a Girl',artist: 'Groove Coverage',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Groove Coverage-God Is a Girl.mp3',duration: 300},
{id: 61,title: 'Groove Coverage-She',artist: 'Groove Coverage',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Groove Coverage-She.mp3',duration: 300},
{id: 62,title: 'Hawk Nelson、Jonathan Steingard-Sold Out',artist: 'Hawk Nelson、Jonathan Steingard',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Hawk Nelson、Jonathan Steingard-Sold Out.mp3',duration: 300},
{id: 63,title: 'HayleyWestenra-never say goodbye',artist: 'HayleyWestenrA',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/HayleyWestenra-never say goodbye.mp3',duration: 300},
{id: 64,title: 'Hedy West-500 Miles',artist: 'Hedy West',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Hedy West-500 Miles.mp3',duration: 300},
{id: 65,title: 'Helene Rolles-My name is Elaine',artist: 'Helene Rolles',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Helene Rolles-My name is Elaine.mp3',duration: 300},
{id: 66,title: 'Ina Wroldsen-I Wanted You',artist: 'Ina Wroldsen',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Ina Wroldsen-I Wanted You.mp3',duration: 300},
{id: 67,title: 'James Blunt-Youre Beautiful',artist: 'James Blunt',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/James Blunt-Youre Beautiful.mp3',duration: 300},
{id: 68,title: 'Jennifer Rush-The Power of Love',artist: 'Jennifer Rush',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Jennifer Rush-The Power of Love.mp3',duration: 300},
{id: 69,title: 'Jewel-Stand',artist: 'Jewel',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Jewel-Stand.mp3',duration: 300},
{id: 70,title: 'Joan Jett-I Hate Myself For Loving You',artist: 'Joan Jett',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Joan Jett-I Hate Myself For Loving You.mp3',duration: 300},
{id: 71,title: 'John Denver-Take Me Home, Country Roads',artist: 'John Denver',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/John Denver-Take Me Home, Country Roads.mp3',duration: 300},
{id: 72,title: 'Justin Bieber、Luis Fonsi、Daddy Yankee-Despacito',artist: 'Justin Bieber、Luis Fonsi、Daddy Yankee',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Justin Bieber、Luis Fonsi、Daddy Yankee-Despacito.mp3',duration: 300},
{id: 73,title: 'Justin Bieber-Baby',artist: 'Justin Bieber',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Justin Bieber-Baby.mp3',duration: 300},
{id: 74,title: 'Kaoma-LambadA',artist: 'KaomA',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Kaoma-Lambada.mp3',duration: 300},
{id: 75,title: 'Katy Perry-Roar',artist: 'Katy Perry',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Katy Perry-Roar.mp3',duration: 300},
{id: 76,title: 'Kelly Clarkson-Because of You',artist: 'Kelly Clarkson',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Kelly Clarkson-Because of You.mp3',duration: 300},
{id: 77,title: 'Kelly Clarkson-Catch My Breath',artist: 'Kelly Clarkson',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Kelly Clarkson-Catch My Breath.mp3',duration: 300},
{id: 78,title: 'Kelly Clarkson-Stronger',artist: 'Kelly Clarkson',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Kelly Clarkson-Stronger.mp3',duration: 300},
{id: 79,title: 'Kim Taylor-I Am You',artist: 'Kim Taylor',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Kim Taylor-I Am You.mp3',duration: 300},
{id: 80,title: 'Klymaxx-I Miss You',artist: 'Klymaxx',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Klymaxx-I Miss You.mp3',duration: 300},
{id: 81,title: 'Ladygaga-Poker Face',artist: 'LadygagA',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Ladygaga-Poker Face.mp3',duration: 300},
{id: 82,title: 'Lenka-The Show',artist: 'LenkA',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Lenka-The Show.mp3',duration: 300},
{id: 83,title: 'Lenka-Trouble Is a Friend',artist: 'LenkA',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Lenka-Trouble Is a Friend.mp3',duration: 300},
{id: 84,title: 'Leo Sayer-More Than I Can Say',artist: 'Leo Sayer',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Leo Sayer-More Than I Can Say.mp3',duration: 300},
{id: 85,title: 'Linkin Park-Numb',artist: 'Linkin Park',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Linkin Park-Numb.mp3',duration: 300},
{id: 86,title: 'LionelRichie-SayYouSayMe',artist: 'LionelRichie',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/LionelRichie-SayYouSayMe.mp3',duration: 300},
{id: 87,title: 'Lovestoned-Bye Bye Bye',artist: 'Lovestoned',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Lovestoned-Bye Bye Bye.mp3',duration: 300},
{id: 88,title: 'Luis Fonsi-Despacito',artist: 'Luis Fonsi',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Luis Fonsi-Despacito.mp3',duration: 300},
{id: 89,title: 'M2M-Pretty Boy',artist: 'M2M',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/M2M-Pretty Boy.mp3',duration: 300},
{id: 90,title: 'M2M-The Day You Went Away',artist: 'M2M',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/M2M-The Day You Went Away.mp3',duration: 300},
{id: 91,title: 'Madonna-Papa Dont Preach',artist: 'MadonnA',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Madonna-Papa Dont Preach.mp3',duration: 300},
{id: 92,title: 'MariaArredondo-Burning',artist: 'MariaArredondo',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/MariaArredondo-Burning.mp3',duration: 300},
{id: 93,title: 'Mark Ronson、Bruno Mars -Uptown Funk',artist: 'Mark Ronson、Bruno Mars ',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Mark Ronson、Bruno Mars -Uptown Funk.mp3',duration: 300},
{id: 94,title: 'Maroon 5-Sugar',artist: 'Maroon 5',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Maroon 5-Sugar.mp3',duration: 300},
{id: 95,title: 'Matthew Lien-Bressanone',artist: 'Matthew Lien',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Matthew Lien-Bressanone.mp3',duration: 300},
{id: 96,title: 'Maxwell-Its Ok',artist: 'Maxwell',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Maxwell-Its Ok.mp3',duration: 300},
{id: 97,title: 'Meg Myers-Running Up That Hill',artist: 'Meg Myers',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Meg Myers-Running Up That Hill.mp3',duration: 300},
{id: 98,title: 'Michael Jackson-Beat It',artist: 'Michael Jackson',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Michael Jackson-Beat It.mp3',duration: 300},
{id: 99,title: 'Michael Jackson-Billie Jean',artist: 'Michael Jackson',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Michael Jackson-Billie Jean.mp3',duration: 300},
{id: 100,title: 'Michael Jackson-Dangerous',artist: 'Michael Jackson',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Michael Jackson-Dangerous.mp3',duration: 300},
{id: 101,title: 'Michael Jackson-HealTheWorld',artist: 'Michael Jackson',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Michael Jackson-HealTheWorld.mp3',duration: 300},
{id: 102,title: 'Michael Jackson-You Are Not Alone',artist: 'Michael Jackson',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Michael Jackson-You Are Not Alone.mp3',duration: 300},
{id: 103,title: 'Michael Learns To Rock-Take Me To Your Heart',artist: 'Michael Learns To Rock',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Michael Learns To Rock-Take Me To Your Heart.mp3',duration: 300},
{id: 104,title: 'MinnieRiperton-LovingYou',artist: 'MinnieRiperton',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/MinnieRiperton-LovingYou.mp3',duration: 300},
{id: 105,title: 'Modern Talking-Brother Louie',artist: 'Modern Talking',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Modern Talking-Brother Louie.mp3',duration: 300},
{id: 106,title: 'Nana-lonely',artist: 'NanA',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Nana-lonely.mp3',duration: 300},
{id: 107,title: 'Nu Virgos-StopStopStop',artist: 'Nu Virgos',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Nu Virgos-StopStopStop.mp3',duration: 300},
{id: 108,title: 'Olly Murs-That Girl',artist: 'Olly Murs',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Olly Murs-That Girl.mp3',duration: 300},
{id: 109,title: 'O-Zone-Dragostea din tei',artist: 'O',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/O-Zone-Dragostea din tei.mp3',duration: 300},
{id: 110,title: 'P!nk-Try',artist: 'P!nk',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/P!nk-Try.mp3',duration: 300},
{id: 111,title: 'R. Kelly-I Believe I Can Fly',artist: 'R. Kelly',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/R. Kelly-I Believe I Can Fly.mp3',duration: 300},
{id: 112,title: 'Rachel Platten-Lone Ranger',artist: 'Rachel Platten',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Rachel Platten-Lone Ranger.mp3',duration: 300},
{id: 113,title: 'Richard Marx-Right Here Waiting',artist: 'Richard Marx',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Richard Marx-Right Here Waiting.mp3',duration: 300},
{id: 114,title: 'Ricky Martin-生命之杯',artist: 'Ricky Martin',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Ricky Martin-生命之杯.mp3',duration: 300},
{id: 115,title: 'Robbie Williams-Better Man',artist: 'Robbie Williams',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Robbie Williams-Better Man.mp3',duration: 300},
{id: 116,title: 'Sarah Brightman、Andrea Bocelli-Time To Say Goodbye',artist: 'Sarah Brightman、Andrea Bocelli',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Sarah Brightman、Andrea Bocelli-Time To Say Goodbye.mp3',duration: 300},
{id: 117,title: 'Sarah Brightman-Scarborough Fair',artist: 'Sarah Brightman',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Sarah Brightman-Scarborough Fair.mp3',duration: 300},
{id: 118,title: 'Sarah Coonor-just one last dance',artist: 'Sarah Coonor',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Sarah Coonor-just one last dance.mp3',duration: 300},
{id: 119,title: 'SarahCoonor-From Sarah With Love',artist: 'SarahCoonor',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/SarahCoonor-From Sarah With Love.mp3',duration: 300},
{id: 120,title: 'Sasha Alex Sloan-Dancing With Your Ghost',artist: 'Sasha Alex Sloan',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Sasha Alex Sloan-Dancing With Your Ghost.mp3',duration: 300},
{id: 121,title: 'Savage Garden-Truly Madly Deeply',artist: 'Savage Garden',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Savage Garden-Truly Madly Deeply.mp3',duration: 300},
{id: 122,title: 'Secret Garden-Nocturne',artist: 'Secret Garden',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Secret Garden-Nocturne.mp3',duration: 300},
{id: 123,title: 'Selena Gomez-Wolves',artist: 'Selena Gomez',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Selena Gomez-Wolves.mp3',duration: 300},
{id: 124,title: 'Shakin Stevens-Because I Love You',artist: 'Shakin Stevens',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Shakin Stevens-Because I Love You.mp3',duration: 300},
{id: 125,title: 'Shayne Ward-Unchained Melody',artist: 'Shayne Ward',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Shayne Ward-Unchained Melody.mp3',duration: 300},
{id: 126,title: 'Sia-Cheap Thrills',artist: 'SiA',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Sia-Cheap Thrills.mp3',duration: 300},
{id: 127,title: 'Sia-Move Your Body',artist: 'SiA',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Sia-Move Your Body.mp3',duration: 300},
{id: 128,title: 'Sia-Unstoppable',artist: 'SiA',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Sia-Unstoppable.mp3',duration: 300},
{id: 129,title: 'Simon And Garfunkel-The Sound of Silence',artist: 'Simon And Garfunkel',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Simon And Garfunkel-The Sound of Silence.mp3',duration: 300},
{id: 130,title: 'Smile.DK-Butterfly',artist: 'Smile.DK',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Smile.DK-Butterfly.mp3',duration: 300},
{id: 131,title: 'Starship-Nothings Gonna Stop Us Now',artist: 'Starship',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Starship-Nothings Gonna Stop Us Now.mp3',duration: 300},
{id: 132,title: 'Stevie Wonder-I Just Called To Say I Love You',artist: 'Stevie Wonder',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Stevie Wonder-I Just Called To Say I Love You.mp3',duration: 300},
{id: 133,title: 'Svetlana Svetikova-where the angel disappears',artist: 'Svetlana SvetikovA',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Svetlana Svetikova-where the angel disappears.mp3',duration: 300},
{id: 134,title: 'Sweetbox-Dont Push Me',artist: 'Sweetbox',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Sweetbox-Dont Push Me.mp3',duration: 300},
{id: 135,title: 'Tatu-30 Minutes',artist: 'Tatu',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Tatu-30 Minutes.mp3',duration: 300},
{id: 136,title: 'Tatu-Loves Me Not',artist: 'Tatu',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Tatu-Loves Me Not.mp3',duration: 300},
{id: 137,title: 'Taylor Swift-Love Story',artist: 'Taylor Swift',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Taylor Swift-Love Story.mp3',duration: 300},
{id: 138,title: 'The Cascades-Rhythm Of The Rain',artist: 'The Cascades',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/The Cascades-Rhythm Of The Rain.mp3',duration: 300},
{id: 139,title: 'The Nolans-Sexy Music',artist: 'The Nolans',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/The Nolans-Sexy Music.mp3',duration: 300},
{id: 140,title: 'The Police-Every Breath You Take',artist: 'The Police',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/The Police-Every Breath You Take.mp3',duration: 300},
{id: 141,title: 'Timbaland-Apologize',artist: 'Timbaland',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Timbaland-Apologize.mp3',duration: 300},
{id: 142,title: 'Trademark-Only Love',artist: 'Trademark',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Trademark-Only Love.mp3',duration: 300},
{id: 143,title: 'Tragedie-Hey Oh',artist: 'Tragedie',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Tragedie-Hey Oh.mp3',duration: 300},
{id: 144,title: 'U2-With Or Without You',artist: 'U2',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/U2-With Or Without You.mp3',duration: 300},
{id: 145,title: 'USA Stars-WeAreTheWorld',artist: 'USA Stars',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/USA Stars-WeAreTheWorld.mp3',duration: 300},
{id: 146,title: 'Usher、Lil Jon、Ludacris-Yeah',artist: 'Usher、Lil Jon、Ludacris',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Usher、Lil Jon、Ludacris-Yeah.mp3',duration: 300},
{id: 147,title: 'Various Artists、Deutschland Sucht Den Superstar-Cry On My Shoulder',artist: 'Various Artists、Deutschland Sucht Den Superstar',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Various Artists、Deutschland Sucht Den Superstar-Cry On My Shoulder.mp3',duration: 300},
{id: 148,title: 'Vicetone、Meron Ryan-Walk Thru Fire',artist: 'Vicetone、Meron Ryan',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Vicetone、Meron Ryan-Walk Thru Fire.mp3',duration: 300},
{id: 149,title: 'Vitas-operA',artist: 'Vitas',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Vitas-opera.mp3',duration: 300},
{id: 150,title: 'Vitas-star',artist: 'Vitas',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Vitas-star.mp3',duration: 300},
{id: 151,title: 'Westlife-My Love',artist: 'Westlife',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Westlife-My Love.mp3',duration: 300},
{id: 152,title: 'Westlife-Nothings Going to Change My Love For You',artist: 'Westlife',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Westlife-Nothings Going to Change My Love For You.mp3',duration: 300},
{id: 153,title: 'Westlife-Seasons in the Sun',artist: 'Westlife',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Westlife-Seasons in the Sun.mp3',duration: 300},
{id: 154,title: 'Whitney Houston-I Have Nothing',artist: 'Whitney Houston',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Whitney Houston-I Have Nothing.mp3',duration: 300},
{id: 155,title: 'Whitney Houston-I will Always Love You',artist: 'Whitney Houston',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Whitney Houston-I will Always Love You.mp3',duration: 300},
{id: 156,title: 'WizKhalifa-See You Again',artist: 'WizKhalifA',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/WizKhalifa-See You Again.mp3',duration: 300},
{id: 157,title: 'Yuri Chika-I Cry',artist: 'Yuri ChikA',src: 'https://cloud.hhhnn.com/d/189Family133/音乐视听/欧美音乐/Yuri Chika-I Cry.mp3',duration: 300}
];

// 如果需要在其他环境中使用，也可导出
// 浏览器环境中直接使用全局变量 MUSIC_DATA
if (typeof module !== 'undefined' && module.exports) {
  module.exports = MUSIC_DATA;
}