DATA("张鹤伦-劳动号子","https://vercel.rryyz.com/free163person/德云社mp3/张鹤伦/张鹤伦-劳动号子.mp3","1");
DATA("张鹤伦-十分美好","https://vercel.rryyz.com/free163person/德云社mp3/张鹤伦/张鹤伦-十分美好.mp3","2");
DATA("张鹤伦-女儿情","https://vercel.rryyz.com/free163person/德云社mp3/张鹤伦/张鹤伦-女儿情.mp3","3");
DATA("张鹤伦-妹妹若是来看我","https://vercel.rryyz.com/free163person/德云社mp3/张鹤伦/张鹤伦-妹妹若是来看我.mp3","4");
DATA("张鹤伦-学小曲 (2)","https://vercel.rryyz.com/free163person/德云社mp3/张鹤伦/张鹤伦-学小曲 (2).mp3","5");
DATA("张鹤伦-学小曲","https://vercel.rryyz.com/free163person/德云社mp3/张鹤伦/张鹤伦-学小曲.mp3","6");
DATA("张鹤伦-德云老司机张鹤伦专场","https://vercel.rryyz.com/free163person/德云社mp3/张鹤伦/张鹤伦-德云老司机张鹤伦专场.mp3","7");
DATA("张鹤伦-快乐节奏","https://vercel.rryyz.com/free163person/德云社mp3/张鹤伦/张鹤伦-快乐节奏.mp3","8");
DATA("张鹤伦-我为歌狂","https://vercel.rryyz.com/free163person/德云社mp3/张鹤伦/张鹤伦-我为歌狂.mp3","9");
DATA("张鹤伦-我是歌手","https://vercel.rryyz.com/free163person/德云社mp3/张鹤伦/张鹤伦-我是歌手.mp3","10");
DATA("张鹤伦-最天使","https://vercel.rryyz.com/free163person/德云社mp3/张鹤伦/张鹤伦-最天使.mp3","11");
DATA("张鹤伦-最炫天团","https://vercel.rryyz.com/free163person/德云社mp3/张鹤伦/张鹤伦-最炫天团.mp3","12");
DATA("张鹤伦-歌曲 因为爱情","https://vercel.rryyz.com/free163person/德云社mp3/张鹤伦/张鹤伦-歌曲 因为爱情.mp3","13");
DATA("张鹤伦-歌曲梦西游","https://vercel.rryyz.com/free163person/德云社mp3/张鹤伦/张鹤伦-歌曲梦西游.mp3","14");
DATA("张鹤伦-流金岁月","https://vercel.rryyz.com/free163person/德云社mp3/张鹤伦/张鹤伦-流金岁月.mp3","15");
DATA("张鹤伦-海阔天空","https://vercel.rryyz.com/free163person/德云社mp3/张鹤伦/张鹤伦-海阔天空.mp3","16");
DATA("张鹤伦-滴答 燃烧的翅膀 北京北京","https://vercel.rryyz.com/free163person/德云社mp3/张鹤伦/张鹤伦-滴答 燃烧的翅膀 北京北京.mp3","17");
DATA("张鹤伦-相思赋予谁","https://vercel.rryyz.com/free163person/德云社mp3/张鹤伦/张鹤伦-相思赋予谁.mp3","18");
DATA("张鹤伦-那些年的歌","https://vercel.rryyz.com/free163person/德云社mp3/张鹤伦/张鹤伦-那些年的歌.mp3","19");
