DATA("adaro-Es_Ist_Ein_Schnee_Gefallen","https://pan.11.wf/free163person/音乐视听/欧美音乐/adaro-Es_Ist_Ein_Schnee_Gefallen.mp3","1");
DATA("AdeleRolling in the Deep(Explicit)","https://pan.11.wf/free163person/音乐视听/欧美音乐/AdeleRolling in the Deep(Explicit).mp3","2");
DATA("Alan WalkerAlone","https://pan.11.wf/free163person/音乐视听/欧美音乐/Alan WalkerAlone.mp3","3");
DATA("Alan WalkerFaded","https://pan.11.wf/free163person/音乐视听/欧美音乐/Alan WalkerFaded.mp3","4");
DATA("AmyDiamond-Heartbeats","https://pan.11.wf/free163person/音乐视听/欧美音乐/AmyDiamond-Heartbeats.mp3","5");
DATA("Ann WinsbornLa La Love On My Mind","https://pan.11.wf/free163person/音乐视听/欧美音乐/Ann WinsbornLa La Love On My Mind.mp3","6");
DATA("AquaMy Oh My","https://pan.11.wf/free163person/音乐视听/欧美音乐/AquaMy Oh My.mp3","7");
DATA("AtlantaRhythmSection-DoItOrDie","https://pan.11.wf/free163person/音乐视听/欧美音乐/AtlantaRhythmSection-DoItOrDie.mp3","8");
DATA("Ava MaxSalt","https://pan.11.wf/free163person/音乐视听/欧美音乐/Ava MaxSalt.mp3","9");
DATA("AvrilLavigne-17","https://pan.11.wf/free163person/音乐视听/欧美音乐/AvrilLavigne-17.mp3","10");
DATA("AvrilLavigne-4Real","https://pan.11.wf/free163person/音乐视听/欧美音乐/AvrilLavigne-4Real.mp3","11");
DATA("AvrilLavigne-Alice","https://pan.11.wf/free163person/音乐视听/欧美音乐/AvrilLavigne-Alice.mp3","12");
DATA("AvrilLavigne-Complicated","https://pan.11.wf/free163person/音乐视听/欧美音乐/AvrilLavigne-Complicated.mp3","13");
DATA("AvrilLavigne-EverybodyHurts","https://pan.11.wf/free163person/音乐视听/欧美音乐/AvrilLavigne-EverybodyHurts.mp3","14");
DATA("AvrilLavigne-Fly","https://pan.11.wf/free163person/音乐视听/欧美音乐/AvrilLavigne-Fly.mp3","15");
DATA("AvrilLavigne-GiveYouWhatYouLike","https://pan.11.wf/free163person/音乐视听/欧美音乐/AvrilLavigne-GiveYouWhatYouLike.mp3","16");
DATA("AvrilLavigne-HeresToNeverGrowingUp(Explicit)","https://pan.11.wf/free163person/音乐视听/欧美音乐/AvrilLavigne-HeresToNeverGrowingUp(Explicit).mp3","17");
DATA("AvrilLavigne-HowYouRemindMe","https://pan.11.wf/free163person/音乐视听/欧美音乐/AvrilLavigne-HowYouRemindMe.mp3","18");
DATA("AvrilLavigne-IamWithYou","https://pan.11.wf/free163person/音乐视听/欧美音乐/AvrilLavigne-IamWithYou.mp3","19");
DATA("AvrilLavigne-Innocence","https://pan.11.wf/free163person/音乐视听/欧美音乐/AvrilLavigne-Innocence.mp3","20");
DATA("AvrilLavigne-NobodysHome","https://pan.11.wf/free163person/音乐视听/欧美音乐/AvrilLavigne-NobodysHome.mp3","21");
DATA("AvrilLavigne-RocknRoll","https://pan.11.wf/free163person/音乐视听/欧美音乐/AvrilLavigne-RocknRoll.mp3","22");
DATA("AvrilLavigne-WishYouWereHere","https://pan.11.wf/free163person/音乐视听/欧美音乐/AvrilLavigne-WishYouWereHere.mp3","23");
DATA("Backstreet BoysEverybody","https://pan.11.wf/free163person/音乐视听/欧美音乐/Backstreet BoysEverybody.mp3","24");
DATA("Backstreet Boysi want it that way","https://pan.11.wf/free163person/音乐视听/欧美音乐/Backstreet Boysi want it that way.mp3","25");
DATA("BackstreetBoys-As_Long_As_You_Love_M","https://pan.11.wf/free163person/音乐视听/欧美音乐/BackstreetBoys-As_Long_As_You_Love_M.mp3","26");
DATA("BertieHiggins-Casablanca","https://pan.11.wf/free163person/音乐视听/欧美音乐/BertieHiggins-Casablanca.mp3","27");
DATA("BertieHiggins-KeyLargo","https://pan.11.wf/free163person/音乐视听/欧美音乐/BertieHiggins-KeyLargo.mp3","28");
DATA("BrunoMars-MarryYou","https://pan.11.wf/free163person/音乐视听/欧美音乐/BrunoMars-MarryYou.mp3","29");
DATA("CaraDillon-Craigie_Hill","https://pan.11.wf/free163person/音乐视听/欧美音乐/CaraDillon-Craigie_Hill.mp3","30");
DATA("ChrisMedina-WhatAreWords","https://pan.11.wf/free163person/音乐视听/欧美音乐/ChrisMedina-WhatAreWords.mp3","31");
DATA("ColdplayYellow","https://pan.11.wf/free163person/音乐视听/欧美音乐/ColdplayYellow.mp3","32");
DATA("Daniel PowterFree Loop","https://pan.11.wf/free163person/音乐视听/欧美音乐/Daniel PowterFree Loop.mp3","33");
DATA("DemiLovato-LetItGo","https://pan.11.wf/free163person/音乐视听/欧美音乐/DemiLovato-LetItGo.mp3","34");
DATA("djokawari-luv_letter","https://pan.11.wf/free163person/音乐视听/欧美音乐/djokawari-luv_letter.mp3","35");
DATA("EdSheeran-ShapeOfYou","https://pan.11.wf/free163person/音乐视听/欧美音乐/EdSheeran-ShapeOfYou.mp3","36");
DATA("emilia-big_big_world","https://pan.11.wf/free163person/音乐视听/欧美音乐/emilia-big_big_world.mp3","37");
DATA("Eminem、Rihanna-LoveTheWayYouLie","https://pan.11.wf/free163person/音乐视听/欧美音乐/Eminem、Rihanna-LoveTheWayYouLie.mp3","38");
DATA("Enya-May It Be","https://pan.11.wf/free163person/音乐视听/欧美音乐/Enya-May It Be.mp3","39");
DATA("enya-Only_Time","https://pan.11.wf/free163person/音乐视听/欧美音乐/enya-Only_Time.mp3","40");
DATA("EraThe Mass","https://pan.11.wf/free163person/音乐视听/欧美音乐/EraThe Mass.mp3","41");
DATA("Gabriel MarianIts My Life","https://pan.11.wf/free163person/音乐视听/欧美音乐/Gabriel MarianIts My Life.mp3","42");
DATA("GrooveCoverage-farAwayFromHome ","https://pan.11.wf/free163person/音乐视听/欧美音乐/GrooveCoverage-farAwayFromHome .mp3","43");
DATA("GrooveCoverage-GodIsaGirl ","https://pan.11.wf/free163person/音乐视听/欧美音乐/GrooveCoverage-GodIsaGirl .mp3","44");
DATA("Hawk Nelson、Jonathan SteingardSold Out","https://pan.11.wf/free163person/音乐视听/欧美音乐/Hawk Nelson、Jonathan SteingardSold Out.mp3","45");
DATA("hayleyWestenra-never say goodbye","https://pan.11.wf/free163person/音乐视听/欧美音乐/hayleyWestenra-never say goodbye.mp3","46");
DATA("Justin Bieber、Luis Fonsi、Daddy Yankee-Despacito(Remix)","https://pan.11.wf/free163person/音乐视听/欧美音乐/Justin Bieber、Luis Fonsi、Daddy Yankee-Despacito(Remix).mp3","47");
DATA("JustinBieber-Baby","https://pan.11.wf/free163person/音乐视听/欧美音乐/JustinBieber-Baby.mp3","48");
DATA("Kelly ClarksonCatch My Breath","https://pan.11.wf/free163person/音乐视听/欧美音乐/Kelly ClarksonCatch My Breath.mp3","49");
DATA("Klymaxx-IMissYou","https://pan.11.wf/free163person/音乐视听/欧美音乐/Klymaxx-IMissYou.mp3","50");
DATA("Ladygaga-Poker Face","https://pan.11.wf/free163person/音乐视听/欧美音乐/Ladygaga-Poker Face.mp3","51");
DATA("Lenka-TheShow","https://pan.11.wf/free163person/音乐视听/欧美音乐/Lenka-TheShow.mp3","52");
DATA("Lenka-TroubleIsaFriend","https://pan.11.wf/free163person/音乐视听/欧美音乐/Lenka-TroubleIsaFriend.mp3","53");
DATA("LeoSayer-MoreThanICanSay","https://pan.11.wf/free163person/音乐视听/欧美音乐/LeoSayer-MoreThanICanSay.mp3","54");
DATA("LionelRichie-SayYouSayMe","https://pan.11.wf/free163person/音乐视听/欧美音乐/LionelRichie-SayYouSayMe.mp3","55");
DATA("LovestonedBye Bye Bye","https://pan.11.wf/free163person/音乐视听/欧美音乐/LovestonedBye Bye Bye.mp3","56");
DATA("Luis Fonsi-Despacito","https://pan.11.wf/free163person/音乐视听/欧美音乐/Luis Fonsi-Despacito.mp3","57");
DATA("M2MPretty Boy","https://pan.11.wf/free163person/音乐视听/欧美音乐/M2MPretty Boy.mp3","58");
DATA("M2MThe Day You Went Away","https://pan.11.wf/free163person/音乐视听/欧美音乐/M2MThe Day You Went Away.mp3","59");
DATA("MariaArredondo-Burning","https://pan.11.wf/free163person/音乐视听/欧美音乐/MariaArredondo-Burning.mp3","60");
DATA("MariahCarey-when you believe","https://pan.11.wf/free163person/音乐视听/欧美音乐/MariahCarey-when you believe.mp3","61");
DATA("MariahCarey-withoutyou","https://pan.11.wf/free163person/音乐视听/欧美音乐/MariahCarey-withoutyou.mp3","62");
DATA("Meg MyersRunning Up That Hill","https://pan.11.wf/free163person/音乐视听/欧美音乐/Meg MyersRunning Up That Hill.mp3","63");
DATA("Michael JacksonYou Are Not Alone","https://pan.11.wf/free163person/音乐视听/欧美音乐/Michael JacksonYou Are Not Alone.mp3","64");
DATA("MinnieRiperton-loving you","https://pan.11.wf/free163person/音乐视听/欧美音乐/MinnieRiperton-loving you.mp3","65");
DATA("MinnieRiperton-LovingYou","https://pan.11.wf/free163person/音乐视听/欧美音乐/MinnieRiperton-LovingYou.mp3","66");
DATA("nana-lonely","https://pan.11.wf/free163person/音乐视听/欧美音乐/nana-lonely.mp3","67");
DATA("Nu VirgosStop!StopStop","https://pan.11.wf/free163person/音乐视听/欧美音乐/Nu VirgosStop!StopStop.mp3","68");
DATA("Olly MursThat Girl","https://pan.11.wf/free163person/音乐视听/欧美音乐/Olly MursThat Girl.mp3","69");
DATA("OnlyTime","https://pan.11.wf/free163person/音乐视听/欧美音乐/OnlyTime.mp3","70");
DATA("Rachel PlattenLone Ranger","https://pan.11.wf/free163person/音乐视听/欧美音乐/Rachel PlattenLone Ranger.mp3","71");
DATA("Robbie WilliamsBetter Man","https://pan.11.wf/free163person/音乐视听/欧美音乐/Robbie WilliamsBetter Man.mp3","72");
DATA("sarahBrightman-斯卡布罗集市","https://pan.11.wf/free163person/音乐视听/欧美音乐/sarahBrightman-斯卡布罗集市.mp3","73");
DATA("SarahConnor-EveryMomentOfMyLife","https://pan.11.wf/free163person/音乐视听/欧美音乐/SarahConnor-EveryMomentOfMyLife.mp3","74");
DATA("SarahCoonor","https://pan.11.wf/free163person/音乐视听/欧美音乐/SarahCoonor.mp3","79");
DATA("SarahCoonor-Are You Ready To Ride","https://pan.11.wf/free163person/音乐视听/欧美音乐/SarahCoonor-Are You Ready To Ride.mp3","75");
DATA("SarahCoonor-color","https://pan.11.wf/free163person/音乐视听/欧美音乐/SarahCoonor-color.mp3","76");
DATA("SarahCoonor-From_Sarah_With_Love","https://pan.11.wf/free163person/音乐视听/欧美音乐/SarahCoonor-From_Sarah_With_Love.mp3","77");
DATA("SarahCoonor-just one last dance","https://pan.11.wf/free163person/音乐视听/欧美音乐/SarahCoonor-just one last dance.mp3","78");
DATA("Sasha Alex SloanDancing With Your Ghost","https://pan.11.wf/free163person/音乐视听/欧美音乐/Sasha Alex SloanDancing With Your Ghost.mp3","80");
DATA("Savage GardenTruly Madly Deeply","https://pan.11.wf/free163person/音乐视听/欧美音乐/Savage GardenTruly Madly Deeply.mp3","81");
DATA("ShakinStevens-BecauseILoveYou","https://pan.11.wf/free163person/音乐视听/欧美音乐/ShakinStevens-BecauseILoveYou.mp3","82");
DATA("SiaMove Your Body(Alan Walker Remix)","https://pan.11.wf/free163person/音乐视听/欧美音乐/SiaMove Your Body(Alan Walker Remix).mp3","83");
DATA("SiaUnstoppable","https://pan.11.wf/free163person/音乐视听/欧美音乐/SiaUnstoppable.mp3","84");
DATA("Sting-ShapeOfMyHeart ","https://pan.11.wf/free163person/音乐视听/欧美音乐/Sting-ShapeOfMyHeart .mp3","85");
DATA("tatu-30_Minutes","https://pan.11.wf/free163person/音乐视听/欧美音乐/tatu-30_Minutes.mp3","86");
DATA("Taylor SwiftLove Story","https://pan.11.wf/free163person/音乐视听/欧美音乐/Taylor SwiftLove Story.mp3","87");
DATA("TrademarkOnly Love","https://pan.11.wf/free163person/音乐视听/欧美音乐/TrademarkOnly Love.mp3","88");
DATA("Vicetone、Meron RyanWalk Thru Fire","https://pan.11.wf/free163person/音乐视听/欧美音乐/Vicetone、Meron RyanWalk Thru Fire.mp3","89");
DATA("WestlifeMy Love","https://pan.11.wf/free163person/音乐视听/欧美音乐/WestlifeMy Love.mp3","90");
DATA("WhitneyHouston-CallYouTonight","https://pan.11.wf/free163person/音乐视听/欧美音乐/WhitneyHouston-CallYouTonight.mp3","91");
DATA("WhitneyHouston-IHaveNothing","https://pan.11.wf/free163person/音乐视听/欧美音乐/WhitneyHouston-IHaveNothing.mp3","92");
DATA("WhitneyHouston-IWillAlwaysLoveYou","https://pan.11.wf/free163person/音乐视听/欧美音乐/WhitneyHouston-IWillAlwaysLoveYou.mp3","93");
DATA("Wiz Khalifa、Charlie PuthSee You Again (feat. Charlie Puth)","https://pan.11.wf/free163person/音乐视听/欧美音乐/Wiz Khalifa、Charlie PuthSee You Again (feat. Charlie Puth).mp3","94");
DATA("WizKhalifa-See You Again","https://pan.11.wf/free163person/音乐视听/欧美音乐/WizKhalifa-See You Again.mp3","95");
DATA("布兰妮-BabyOneMoreTime","https://pan.11.wf/free163person/音乐视听/欧美音乐/布兰妮-BabyOneMoreTime.mp3","99");
DATA("布兰妮-everytime","https://pan.11.wf/free163person/音乐视听/欧美音乐/布兰妮-everytime.mp3","100");
DATA("卡洛儿-假如爱有天意","https://pan.11.wf/free163person/音乐视听/欧美音乐/卡洛儿-假如爱有天意.mp3","97");
DATA("卡洛儿-写给海洋","https://pan.11.wf/free163person/音乐视听/欧美音乐/卡洛儿-写给海洋.mp3","98");
DATA("卡朋特-YesterdayOnceMore","https://pan.11.wf/free163person/音乐视听/欧美音乐/卡朋特-YesterdayOnceMore.mp3","96");
DATA("马克尔杰克逊-HealTheWorld","https://pan.11.wf/free163person/音乐视听/欧美音乐/马克尔杰克逊-HealTheWorld.mp3","108");
DATA("欧美群星-WeAreTheWorld","https://pan.11.wf/free163person/音乐视听/欧美音乐/欧美群星-WeAreTheWorld.mp3","104");
DATA("手嶌葵-the rose","https://pan.11.wf/free163person/音乐视听/欧美音乐/手嶌葵-the rose.mp3","101");
DATA("斯维特拉娜 斯维吉科娃-天使消逝的地方","https://pan.11.wf/free163person/音乐视听/欧美音乐/斯维特拉娜 斯维吉科娃-天使消逝的地方.mp3","102");
DATA("铁达尼号主题曲-MyHeartWillGoOn","https://pan.11.wf/free163person/音乐视听/欧美音乐/铁达尼号主题曲-MyHeartWillGoOn.mp3","107");
DATA("维塔斯-海豚音","https://pan.11.wf/free163person/音乐视听/欧美音乐/维塔斯-海豚音.mp3","105");
DATA("英文经典-我的名字叫伊莲","https://pan.11.wf/free163person/音乐视听/欧美音乐/英文经典-我的名字叫伊莲.mp3","106");
DATA("有里知花-I_Cry","https://pan.11.wf/free163person/音乐视听/欧美音乐/有里知花-I_Cry.mp3","103");
