DATA("AtlantaRhythmSection-DoItOrDie","https://pan.11.wf/free163person/音乐视听/欧美音乐/AtlantaRhythmSection-DoItOrDie.mp3","1");
DATA("AvrilLavigne-17","https://pan.11.wf/free163person/音乐视听/欧美音乐/AvrilLavigne-17.mp3","2");
DATA("AvrilLavigne-4Real","https://pan.11.wf/free163person/音乐视听/欧美音乐/AvrilLavigne-4Real.mp3","3");
DATA("AvrilLavigne-Alice","https://pan.11.wf/free163person/音乐视听/欧美音乐/AvrilLavigne-Alice.mp3","4");
DATA("AvrilLavigne-Complicated","https://pan.11.wf/free163person/音乐视听/欧美音乐/AvrilLavigne-Complicated.mp3","5");
DATA("AvrilLavigne-EverybodyHurts","https://pan.11.wf/free163person/音乐视听/欧美音乐/AvrilLavigne-EverybodyHurts.mp3","6");
DATA("AvrilLavigne-Fly","https://pan.11.wf/free163person/音乐视听/欧美音乐/AvrilLavigne-Fly.mp3","7");
DATA("AvrilLavigne-GiveYouWhatYouLike","https://pan.11.wf/free163person/音乐视听/欧美音乐/AvrilLavigne-GiveYouWhatYouLike.mp3","8");
DATA("AvrilLavigne-HeresToNeverGrowingUp(Explicit)","https://pan.11.wf/free163person/音乐视听/欧美音乐/AvrilLavigne-HeresToNeverGrowingUp(Explicit).mp3","9");
DATA("AvrilLavigne-HowYouRemindMe","https://pan.11.wf/free163person/音乐视听/欧美音乐/AvrilLavigne-HowYouRemindMe.mp3","10");
DATA("AvrilLavigne-IamWithYou","https://pan.11.wf/free163person/音乐视听/欧美音乐/AvrilLavigne-IamWithYou.mp3","11");
DATA("AvrilLavigne-Innocence","https://pan.11.wf/free163person/音乐视听/欧美音乐/AvrilLavigne-Innocence.mp3","12");
DATA("AvrilLavigne-NobodysHome","https://pan.11.wf/free163person/音乐视听/欧美音乐/AvrilLavigne-NobodysHome.mp3","13");
DATA("AvrilLavigne-RocknRoll","https://pan.11.wf/free163person/音乐视听/欧美音乐/AvrilLavigne-RocknRoll.mp3","14");
DATA("AvrilLavigne-WishYouWereHere","https://pan.11.wf/free163person/音乐视听/欧美音乐/AvrilLavigne-WishYouWereHere.mp3","15");
DATA("BackstreetBoys-As_Long_As_You_Love_M","https://pan.11.wf/free163person/音乐视听/欧美音乐/BackstreetBoys-As_Long_As_You_Love_M.mp3","16");
DATA("bertiehiggins-casablanca","https://pan.11.wf/free163person/音乐视听/欧美音乐/bertiehiggins-casablanca.mp3","17");
DATA("BertieHiggins-KeyLargo","https://pan.11.wf/free163person/音乐视听/欧美音乐/BertieHiggins-KeyLargo.mp3","18");
DATA("BrunoMars-MarryYou","https://pan.11.wf/free163person/音乐视听/欧美音乐/BrunoMars-MarryYou.mp3","19");
DATA("ChrisMedina-WhatAreWords","https://pan.11.wf/free163person/音乐视听/欧美音乐/ChrisMedina-WhatAreWords.mp3","20");
DATA("DemiLovato-LetItGo","https://pan.11.wf/free163person/音乐视听/欧美音乐/DemiLovato-LetItGo.mp3","21");
DATA("EdSheeran-ShapeOfYou","https://pan.11.wf/free163person/音乐视听/欧美音乐/EdSheeran-ShapeOfYou.mp3","22");
DATA("emilia-big_big_world","https://pan.11.wf/free163person/音乐视听/欧美音乐/emilia-big_big_world.mp3","23");
DATA("Eminem、Rihanna-LoveTheWayYouLie","https://pan.11.wf/free163person/音乐视听/欧美音乐/Eminem、Rihanna-LoveTheWayYouLie.mp3","24");
DATA("GrooveCoverage-farAwayFromHome ","https://pan.11.wf/free163person/音乐视听/欧美音乐/GrooveCoverage-farAwayFromHome .mp3","25");
DATA("GrooveCoverage-GodIsaGirl ","https://pan.11.wf/free163person/音乐视听/欧美音乐/GrooveCoverage-GodIsaGirl .mp3","26");
DATA("JustinBieber-Baby","https://pan.11.wf/free163person/音乐视听/欧美音乐/JustinBieber-Baby.mp3","27");
DATA("Klymaxx-IMissYou","https://pan.11.wf/free163person/音乐视听/欧美音乐/Klymaxx-IMissYou.mp3","28");
DATA("Ladygaga-Poker Face","https://pan.11.wf/free163person/音乐视听/欧美音乐/Ladygaga-Poker Face.mp3","29");
DATA("Lenka-TheShow","https://pan.11.wf/free163person/音乐视听/欧美音乐/Lenka-TheShow.mp3","30");
DATA("Lenka-TroubleIsaFriend","https://pan.11.wf/free163person/音乐视听/欧美音乐/Lenka-TroubleIsaFriend.mp3","31");
DATA("LeoSayer-MoreThanICanSay","https://pan.11.wf/free163person/音乐视听/欧美音乐/LeoSayer-MoreThanICanSay.mp3","32");
DATA("LionelRichie-SayYouSayMe","https://pan.11.wf/free163person/音乐视听/欧美音乐/LionelRichie-SayYouSayMe.mp3","33");
DATA("MariaArredondo-Burning","https://pan.11.wf/free163person/音乐视听/欧美音乐/MariaArredondo-Burning.mp3","34");
DATA("MariahCarey-when you believe","https://pan.11.wf/free163person/音乐视听/欧美音乐/MariahCarey-when you believe.mp3","35");
DATA("MariahCarey-withoutyou","https://pan.11.wf/free163person/音乐视听/欧美音乐/MariahCarey-withoutyou.mp3","36");
DATA("MinnieRiperton-loving you","https://pan.11.wf/free163person/音乐视听/欧美音乐/MinnieRiperton-loving you.mp3","37");
DATA("MinnieRiperton-LovingYou","https://pan.11.wf/free163person/音乐视听/欧美音乐/MinnieRiperton-LovingYou.mp3","38");
DATA("nana-lonely","https://pan.11.wf/free163person/音乐视听/欧美音乐/nana-lonely.mp3","39");
DATA("OnlyTime","https://pan.11.wf/free163person/音乐视听/欧美音乐/OnlyTime.mp3","40");
DATA("SarahConnor-EveryMomentOfMyLife","https://pan.11.wf/free163person/音乐视听/欧美音乐/SarahConnor-EveryMomentOfMyLife.mp3","41");
DATA("SarahCoonor-Are You Ready To Ride","https://pan.11.wf/free163person/音乐视听/欧美音乐/SarahCoonor-Are You Ready To Ride.mp3","42");
DATA("SarahCoonor-color","https://pan.11.wf/free163person/音乐视听/欧美音乐/SarahCoonor-color.mp3","43");
DATA("SarahCoonor-From_Sarah_With_Love","https://pan.11.wf/free163person/音乐视听/欧美音乐/SarahCoonor-From_Sarah_With_Love.mp3","44");
DATA("SarahCoonor-just one last dance","https://pan.11.wf/free163person/音乐视听/欧美音乐/SarahCoonor-just one last dance.mp3","45");
DATA("SarahCoonor","https://pan.11.wf/free163person/音乐视听/欧美音乐/SarahCoonor.mp3","46");
DATA("ShakinStevens-BecauseILoveYou","https://pan.11.wf/free163person/音乐视听/欧美音乐/ShakinStevens-BecauseILoveYou.mp3","47");
DATA("Sting-ShapeOfMyHeart ","https://pan.11.wf/free163person/音乐视听/欧美音乐/Sting-ShapeOfMyHeart .mp3","48");
DATA("WhitneyHouston-CallYouTonight","https://pan.11.wf/free163person/音乐视听/欧美音乐/WhitneyHouston-CallYouTonight.mp3","49");
DATA("WhitneyHouston-IHaveNothing","https://pan.11.wf/free163person/音乐视听/欧美音乐/WhitneyHouston-IHaveNothing.mp3","50");
DATA("WhitneyHouston-IWillAlwaysLoveYou","https://pan.11.wf/free163person/音乐视听/欧美音乐/WhitneyHouston-IWillAlwaysLoveYou.mp3","51");
DATA("WizKhalifa-See You Again","https://pan.11.wf/free163person/音乐视听/欧美音乐/WizKhalifa-See You Again.mp3","52");
DATA("卡朋特-YesterdayOnceMore","https://pan.11.wf/free163person/音乐视听/欧美音乐/卡朋特-YesterdayOnceMore.mp3","53");
DATA("布兰妮-BABYONEMORETIME","https://pan.11.wf/free163person/音乐视听/欧美音乐/布兰妮-BABYONEMORETIME.mp3","54");
DATA("布兰妮-everytime","https://pan.11.wf/free163person/音乐视听/欧美音乐/布兰妮-everytime.mp3","55");
DATA("欧美群星-WeAreTheWorld","https://pan.11.wf/free163person/音乐视听/欧美音乐/欧美群星-WeAreTheWorld.mp3","56");
DATA("维塔斯-海豚音","https://pan.11.wf/free163person/音乐视听/欧美音乐/维塔斯-海豚音.mp3","57");
DATA("英文经典-我的名字叫伊莲","https://pan.11.wf/free163person/音乐视听/欧美音乐/英文经典-我的名字叫伊莲.mp3","58");
DATA("铁达尼号主题曲-MyHeartWillGoOn","https://pan.11.wf/free163person/音乐视听/欧美音乐/铁达尼号主题曲-MyHeartWillGoOn.mp3","59");
DATA("马克尔杰克逊-HealTheWorld","https://pan.11.wf/free163person/音乐视听/欧美音乐/马克尔杰克逊-HealTheWorld.mp3","60");