DATA("2NE1-Fire","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/2NE1-Fire.mp3","1");
DATA("Baby V.O.X-Get Up","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/Baby V.O.X-Get Up.mp3","2");
DATA("Baby V.O.X-Killer","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/Baby V.O.X-Killer.mp3","3");
DATA("Baby V.O.X-Why","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/Baby V.O.X-Why.mp3","4");
DATA("Baby V.O.X-偶然","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/Baby V.O.X-偶然.mp3","5");
DATA("BoA-AmazingKiss","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/BoA-AmazingKiss.mp3","6");
DATA("BoA-ListenToMyHeart","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/BoA-ListenToMyHeart.mp3","7");
DATA("BoA-No1","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/BoA-No1.mp3","8");
DATA("Dana-到世界尽头","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/Dana-到世界尽头.mp3","9");
DATA("Davichi-爱情和战争","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/Davichi-爱情和战争.mp3","10");
DATA("Davichi-悲伤的约定","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/Davichi-悲伤的约定.mp3","11");
DATA("Davichi-即使恨也爱你","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/Davichi-即使恨也爱你.mp3","12");
DATA("Davichi-可笑的爱情","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/Davichi-可笑的爱情.mp3","13");
DATA("Davichi-这份爱","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/Davichi-这份爱.mp3","14");
DATA("DreamGirls殆死悲爱-ImSorry","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/DreamGirls殆死悲爱-ImSorry.mp3","15");
DATA("Fin.K.L-BlueRain","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/Fin.K.L-BlueRain.mp3","16");
DATA("i-dle-Queencard","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/i-dle-Queencard.mp3","17");
DATA("i-dle-TOMBOY","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/i-dle-TOMBOY.mp3","18");
DATA("jewelry-again","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/jewelry-again.mp3","19");
DATA("jewelry-Super_Star","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/jewelry-Super_Star.mp3","20");
DATA("Jewelry-更喜欢你","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/Jewelry-更喜欢你.mp3","21");
DATA("Kara-Honey","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/Kara-Honey.mp3","22");
DATA("kiss-因为是女子","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/kiss-因为是女子.mp3","23");
DATA("Lyn-爱情都是谎言","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/Lyn-爱情都是谎言.mp3","24");
DATA("Lyn-歌信","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/Lyn-歌信.mp3","25");
DATA("Psy-江南Style","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/Psy-江南Style.mp3","26");
DATA("rania-DrFeelGood","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/rania-DrFeelGood.mp3","27");
DATA("S.E.S.-Dreams Come True","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/S.E.S.-Dreams Come True.mp3","28");
DATA("S.E.S.-Just In Love","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/S.E.S.-Just In Love.mp3","29");
DATA("S.E.S.-Love","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/S.E.S.-Love.mp3","30");
DATA("S.E.S.-Oh My Love","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/S.E.S.-Oh My Love.mp3","31");
DATA("S.E.S.-Sha-La-La","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/S.E.S.-Sha-La-La.mp3","32");
DATA("S.E.S.-Twilight Zone","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/S.E.S.-Twilight Zone.mp3","33");
DATA("S.E.S.-U","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/S.E.S.-U.mp3","34");
DATA("sHarp-我的嘴唇如暖暖的咖啡","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/sHarp-我的嘴唇如暖暖的咖啡.mp3","35");
DATA("T-ara-DAY BY DAY","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/T-ara-DAY BY DAY.mp3","36");
DATA("T-ara-LoveyDovey","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/T-ara-LoveyDovey.mp3","37");
DATA("T-ara-Sexy Love","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/T-ara-Sexy Love.mp3","38");
DATA("WAX","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/WAX.mp3","39");
DATA("WAX-Money","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/WAX-Money.mp3","40");
DATA("WAX-改变化装","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/WAX-改变化装.mp3","41");
DATA("WAX-渴望爱情","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/WAX-渴望爱情.mp3","42");
DATA("WAX-一通电话也不行","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/WAX-一通电话也不行.mp3","43");
DATA("WAX-余情","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/WAX-余情.mp3","44");
DATA("WAX-只有眼泪只有眼泪","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/WAX-只有眼泪只有眼泪.mp3","45");
DATA("WAX-坐着地铁","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/WAX-坐着地铁.mp3","46");
DATA("WonderGirls-nobody","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/WonderGirls-nobody.mp3","47");
DATA("白智英-不再爱了","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/白智英-不再爱了.mp3","48");
DATA("白智英-那个女人","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/白智英-那个女人.mp3","49");
DATA("白智英-像中枪一样","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/白智英-像中枪一样.mp3","50");
DATA("蔡妍-My Love","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/蔡妍-My Love.mp3","51");
DATA("蔡妍-两个人","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/蔡妍-两个人.mp3","52");
DATA("蔡妍-危险的演出","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/蔡妍-危险的演出.mp3","53");
DATA("蔡妍-摇摆","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/蔡妍-摇摆.mp3","54");
DATA("冬季恋歌-从开始到现在","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/冬季恋歌-从开始到现在.mp3","55");
DATA("高耀太-悲梦","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/高耀太-悲梦.mp3","56");
DATA("高耀太-波澜","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/高耀太-波澜.mp3","57");
DATA("高耀太-纯情","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/高耀太-纯情.mp3","58");
DATA("高耀太-飞翔","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/高耀太-飞翔.mp3","59");
DATA("高耀太-火花","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/高耀太-火花.mp3","60");
DATA("高耀太-失恋","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/高耀太-失恋.mp3","61");
DATA("高耀太-英雄","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/高耀太-英雄.mp3","62");
DATA("高耀太-诱惑","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/高耀太-诱惑.mp3","63");
DATA("洪真英-活着","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/洪真英-活着.mp3","64");
DATA("金智贤-呼唤1","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/金智贤-呼唤1.mp3","65");
DATA("李宝蓝-红豆2","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/李宝蓝-红豆2.mp3","66");
DATA("李海丽-红豆1","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/李海丽-红豆1.mp3","67");
DATA("李孝利-10minutes","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/李孝利-10minutes.mp3","68");
DATA("李秀英-AlsoILoveYou","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/李秀英-AlsoILoveYou.mp3","69");
DATA("李秀英-NEVERAGAIN","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/李秀英-NEVERAGAIN.mp3","70");
DATA("李秀英-我们","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/李秀英-我们.mp3","71");
DATA("李贞贤-阿里阿里","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/李贞贤-阿里阿里.mp3","72");
DATA("李贞贤-半","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/李贞贤-半.mp3","73");
DATA("李贞贤-发疯","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/李贞贤-发疯.mp3","74");
DATA("李贞贤-换掉","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/李贞贤-换掉.mp3","75");
DATA("李贞贤-哇","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/李贞贤-哇.mp3","76");
DATA("李贞贤-月亮啊月亮","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/李贞贤-月亮啊月亮.mp3","77");
DATA("柳真-ChaCha","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/柳真-ChaCha.mp3","78");
DATA("米娜-Kiss Kiss","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/米娜-Kiss Kiss.mp3","79");
DATA("米娜-电话情缘","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/米娜-电话情缘.mp3","80");
DATA("米娜-转","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/米娜-转.mp3","81");
DATA("裴勇俊-MyMemory","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/裴勇俊-MyMemory.mp3","82");
DATA("朴惠京-RAIN","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/朴惠京-RAIN.mp3","83");
DATA("朴慧京-yesterday","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/朴慧京-yesterday.mp3","84");
DATA("朴慧京-结婚","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/朴慧京-结婚.mp3","85");
DATA("朴孝信-花信","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/朴孝信-花信.mp3","86");
DATA("朴孝信-雪之花","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/朴孝信-雪之花.mp3","87");
DATA("朴志胤-Steal Away","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/朴志胤-Steal Away.mp3","88");
DATA("朴志胤-成人礼","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/朴志胤-成人礼.mp3","89");
DATA("少女时代-Animal","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-Animal.mp3","90");
DATA("少女时代-BeepBeep","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-BeepBeep.mp3","91");
DATA("少女时代-GalaxySupernova","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-GalaxySupernova.mp3","92");
DATA("少女时代-Gee(Japanesever.)","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-Gee(Japanesever.).mp3","93");
DATA("少女时代-Gee","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-Gee.mp3","94");
DATA("少女时代-Holiday","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-Holiday.mp3","95");
DATA("少女时代-HOOT","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-HOOT.mp3","96");
DATA("少女时代-IntoTheNewWorld","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-IntoTheNewWorld.mp3","97");
DATA("少女时代-Mr.Mr.(Japanesever.)","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-Mr.Mr.(Japanesever.).mp3","98");
DATA("少女时代-MrTaxi","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-MrTaxi.mp3","99");
DATA("少女时代-Oh!(Japanesever.)","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-Oh!(Japanesever.).mp3","100");
DATA("少女时代-Oh!","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-Oh!.mp3","101");
DATA("少女时代-Paparazzi","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-Paparazzi.mp3","102");
DATA("少女时代-PARTY","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-PARTY.mp3","103");
DATA("少女时代-RunDevilRun","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-RunDevilRun.mp3","104");
DATA("少女时代-TheBoys","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/少女时代-TheBoys.mp3","105");
DATA("申彗星-LoveLetter","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/申彗星-LoveLetter.mp3","106");
DATA("申彗星-爱情病","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/申彗星-爱情病.mp3","107");
DATA("申彗星-我慢慢死去","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/申彗星-我慢慢死去.mp3","108");
DATA("申彗星-在那个位置","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/申彗星-在那个位置.mp3","109");
DATA("申升勋-我相信","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/申升勋-我相信.mp3","110");
DATA("淑熙-啦啦啦","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/淑熙-啦啦啦.mp3","111");
DATA("宋雨琦-Radio","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/宋雨琦-Radio.mp3","112");
DATA("孙丹菲-星期六晚上","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/孙丹菲-星期六晚上.mp3","113");
DATA("太妍-如果","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/太妍-如果.mp3","114");
DATA("太妍-四季","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/太妍-四季.mp3","115");
DATA("吴贤兰-Remember","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/吴贤兰-Remember.mp3","116");
DATA("孝琳-再见","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/孝琳-再见.mp3","117");
DATA("严正花-都走吧","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/严正花-都走吧.mp3","118");
DATA("玉珠铉-仲夏夜之梦","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/玉珠铉-仲夏夜之梦.mp3","119");
DATA("张娜拉-Sweet Dream","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/张娜拉-Sweet Dream.mp3","120");
DATA("郑日英-祈祷","https://cloud.hhhnn.com/d/189Family133/音乐视听/韩国音乐/郑日英-祈祷.mp3","121");