//日韩音乐
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/日本音乐/azu-angel.mp3","azu-angel");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/日本音乐/juju-この夜を止めてよ.mp3","juju-この夜を止めてよ");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/日本音乐/rania-DrFeelGood.mp3","rania-DrFeelGood");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/日本音乐/滨崎步-A_Song_For_Xx.mp3","滨崎步-A_Song_For_Xx");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/日本音乐/滨崎步-Blue_Bird.mp3","滨崎步-Blue_Bird");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/日本音乐/滨崎步-depend_on_you.mp3","滨崎步-depend_on_you");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/日本音乐/滨崎步-fly_high.mp3","滨崎步-fly_high");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/日本音乐/滨崎步-M.mp3","滨崎步-M");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/日本音乐/滨崎步-To_Be.mp3","滨崎步-To_Be");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/日本音乐/初音未来-甩葱歌.mp3","初音未来-甩葱歌");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/日本音乐/川嶋あい-大丈夫だよ.mp3","川嶋あい-大丈夫だよ");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/日本音乐/大冢爱-プラネタリウム.mp3","大冢爱-プラネタリウム");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/日本音乐/大冢爱-桃ノ花ビラ.mp3","大冢爱-桃ノ花ビラ");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/日本音乐/谷村新司-いい日旅立ち.mp3","谷村新司-いい日旅立ち");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/日本音乐/谷村新司-カノン.mp3","谷村新司-カノン");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/日本音乐/谷村新司-昂一すばゐ.mp3","谷村新司-昂一すばゐ");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/日本音乐/谷村新司-风姿花传.mp3","谷村新司-风姿花传");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/日本音乐/谷村新司-君の歌.mp3","谷村新司-君の歌");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/日本音乐/谷村新司-睡莲.mp3","谷村新司-睡莲");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/日本音乐/谷村新司-忘れないで.mp3","谷村新司-忘れないで");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/日本音乐/谷村新司-星.mp3","谷村新司-星");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/日本音乐/日本歌曲 星の在り処.mp3","日本歌曲 星の在り処");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/日本音乐/日本歌曲-漠然の莹.mp3","日本歌曲-漠然の莹");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/日本音乐/少女时代-mr taxi.mp3","少女时代-mr taxi");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/日本音乐/少女时代-the boys.mp3","少女时代-the boys");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/日本音乐/宇多田光-First_Love.mp3","宇多田光-First_Love");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/日本音乐/中岛美嘉-雪華.mp3","中岛美嘉-雪華");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/日本音乐/中島みゆき-容易受伤的女人原曲.mp3","中島みゆき-容易受伤的女人原曲");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/日本音乐/宗次郎-故乡的原风景.mp3","宗次郎-故乡的原风景");