//纯音乐
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-爱在四月雪.mp3","纯音乐-爱在四月雪");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-安魂曲.mp3","纯音乐-安魂曲");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-安妮的歌.mp3","纯音乐-安妮的歌");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-宝贝珍之歌.mp3","纯音乐-宝贝珍之歌");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-沉睡的森林.mp3","纯音乐-沉睡的森林");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-沉思曲.mp3","纯音乐-沉思曲");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-初恋的地方.mp3","纯音乐-初恋的地方");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-春之声圆舞曲 古典钢琴.mp3","纯音乐-春之声圆舞曲 古典钢琴");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-大溪地清流 米奴哀舞.mp3","纯音乐-大溪地清流 米奴哀舞");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-第六感生死恋.mp3","纯音乐-第六感生死恋");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-断情殇.mp3","纯音乐-断情殇");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-飞鼠溪.mp3","纯音乐-飞鼠溪");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-风的气息.mp3","纯音乐-风的气息");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-风中之尘.mp3","纯音乐-风中之尘");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-格里格索尔维格之歌.mp3","纯音乐-格里格索尔维格之歌");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-和兰花在一起.mp3","纯音乐-和兰花在一起");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-很好听.mp3","纯音乐-很好听");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-火宵之月.mp3","纯音乐-火宵之月");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-卡布里的月光.mp3","纯音乐-卡布里的月光");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-卡农钢琴曲.mp3","纯音乐-卡农钢琴曲");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-蓝色的爱.mp3","纯音乐-蓝色的爱");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-梁祝之化蝶 笛子.mp3","纯音乐-梁祝之化蝶 笛子");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-绵雪.mp3","纯音乐-绵雪");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-茉莉花.mp3","纯音乐-茉莉花");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-森林中的一天.mp3","纯音乐-森林中的一天");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-似曾相识.mp3","纯音乐-似曾相识");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-守护你的天使.mp3","纯音乐-守护你的天使");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-树蛙之歌.mp3","纯音乐-树蛙之歌");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-水之轮回.mp3","纯音乐-水之轮回");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-天鹅湖.mp3","纯音乐-天鹅湖");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-万福玛丽亚.mp3","纯音乐-万福玛丽亚");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-我的海洋.mp3","纯音乐-我的海洋");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-西班牙斗牛士进行曲.mp3","纯音乐-西班牙斗牛士进行曲");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-西藏的月.mp3","纯音乐-西藏的月");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-昔日情怀.mp3","纯音乐-昔日情怀");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-夏日华尔兹.mp3","纯音乐-夏日华尔兹");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-乡间晚风.mp3","纯音乐-乡间晚风");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-相识也是缘份.mp3","纯音乐-相识也是缘份");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-小步舞曲.mp3","纯音乐-小步舞曲");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-小雨落在你脸上.mp3","纯音乐-小雨落在你脸上");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-雪之梦.mp3","纯音乐-雪之梦");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-野鸟情歌.mp3","纯音乐-野鸟情歌");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-印象之旅.mp3","纯音乐-印象之旅");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-雨林深处.mp3","纯音乐-雨林深处");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-雨中漫步.mp3","纯音乐-雨中漫步");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-月光下的凤尾竹.mp3","纯音乐-月光下的凤尾竹");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-云淡风轻.mp3","纯音乐-云淡风轻");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-只此一生.mp3","纯音乐-只此一生");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Chunyy-最终幻想.mp3","纯音乐-最终幻想");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/Joanie madden-The level plain.mp3","Joanie madden-The level plain");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/yiruma-雨的印记.mp3","yiruma-雨的印记");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/爱尔兰风笛 漫步神秘园.mp3","爱尔兰风笛 漫步神秘园");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/爱尔兰口哨女皇madden-爱尔兰画眉.mp3","爱尔兰口哨女皇madden-爱尔兰画眉");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-chariots of fire.mp3","班得瑞-chariots of fire");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-diamonds.mp3","班得瑞-diamonds");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-EI condor pasa.mp3","班得瑞-EI condor pasa");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-i want to know love is.mp3","班得瑞-i want to know love is");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-i_swear.mp3","班得瑞-i_swear");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-imagine.mp3","班得瑞-imagine");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-into red velvet.mp3","班得瑞-into red velvet");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-moment of fantasy.mp3","班得瑞-moment of fantasy");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-one moment in time.mp3","班得瑞-one moment in time");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-tenderness.mp3","班得瑞-tenderness");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-the sounds of silence.mp3","班得瑞-the sounds of silence");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-tims lullaby.mp3","班得瑞-tims lullaby");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-安妮的仙境.mp3","班得瑞-安妮的仙境");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-变幻之风.mp3","班得瑞-变幻之风");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-晨光.mp3","班得瑞-晨光");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-初雪.mp3","班得瑞-初雪");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-春水.mp3","班得瑞-春水");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-春野.mp3","班得瑞-春野");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-非洲日落.mp3","班得瑞-非洲日落");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-风的呢喃.mp3","班得瑞-风的呢喃");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-海王星.mp3","班得瑞-海王星");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-火战车.mp3","班得瑞-火战车");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-涟漪.mp3","班得瑞-涟漪");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-马可波罗.mp3","班得瑞-马可波罗");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-满天星.mp3","班得瑞-满天星");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-秘密.mp3","班得瑞-秘密");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-排箫 老鹰之歌.mp3","班得瑞-排箫 老鹰之歌");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-清晨.mp3","班得瑞-清晨");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-日光海岸.mp3","班得瑞-日光海岸");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-天堂之门.mp3","班得瑞-天堂之门");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-微风山谷.mp3","班得瑞-微风山谷");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-无止境的见识.mp3","班得瑞-无止境的见识");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-夏日华尔兹.mp3","班得瑞-夏日华尔兹");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-仙境.mp3","班得瑞-仙境");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-依卡路斯的羽翼.mp3","班得瑞-依卡路斯的羽翼");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-忧郁的爱.mp3","班得瑞-忧郁的爱");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-月光.mp3","班得瑞-月光");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-追梦人.mp3","班得瑞-追梦人");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班得瑞-紫蝴蝶.mp3","班得瑞-紫蝴蝶");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/班德瑞-巴格达的星星.mp3","班德瑞-巴格达的星星");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/贝多芬-悲怆奏鸣曲.mp3","贝多芬-悲怆奏鸣曲");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/贝多芬-命运交响乐.mp3","贝多芬-命运交响乐");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/贝多芬-田园交响曲.mp3","贝多芬-田园交响曲");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/贝多芬-月光奏鸣曲.mp3","贝多芬-月光奏鸣曲");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/杜普雷-殇.mp3","杜普雷-殇");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/宫崎骏 龙猫-水晶音乐.mp3","宫崎骏 龙猫-水晶音乐");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/久石让-天空之城.mp3","久石让-天空之城");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/凯文柯恩-走过绿意.mp3","凯文柯恩-走过绿意");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/浪客剑心-In Memories “A boy meets The Man”.mp3","浪客剑心-In Memories “A boy meets The Man”");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/李斯特-钟.mp3","李斯特-钟");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-爱的纪念.mp3","理查德 克莱德曼-爱的纪念");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-爱的协奏曲.mp3","理查德 克莱德曼-爱的协奏曲");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-爱之梦.mp3","理查德 克莱德曼-爱之梦");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-出埃及记.mp3","理查德 克莱德曼-出埃及记");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-给母亲的信.mp3","理查德 克莱德曼-给母亲的信");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-海边的祈祷.mp3","理查德 克莱德曼-海边的祈祷");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-海边的星空.mp3","理查德 克莱德曼-海边的星空");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-欢乐颂.mp3","理查德 克莱德曼-欢乐颂");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-欢乐之歌.mp3","理查德 克莱德曼-欢乐之歌");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-蓝色的爱.mp3","理查德 克莱德曼-蓝色的爱");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-蓝色狂想曲.mp3","理查德 克莱德曼-蓝色狂想曲");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-罗密欧与朱丽叶.mp3","理查德 克莱德曼-罗密欧与朱丽叶");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-玫瑰色的人生.mp3","理查德 克莱德曼-玫瑰色的人生");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-梦中的婚礼.mp3","理查德 克莱德曼-梦中的婚礼");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-梦中的鸟.mp3","理查德 克莱德曼-梦中的鸟");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-秘密的庭院.mp3","理查德 克莱德曼-秘密的庭院");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-乒乓之恋.mp3","理查德 克莱德曼-乒乓之恋");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-秋日私语.mp3","理查德 克莱德曼-秋日私语");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-柔如彩虹.mp3","理查德 克莱德曼-柔如彩虹");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-伤感乐曲.mp3","理查德 克莱德曼-伤感乐曲");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-少女的祈祷.mp3","理查德 克莱德曼-少女的祈祷");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-水边的阿狄丽娜.mp3","理查德 克莱德曼-水边的阿狄丽娜");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-思乡曲.mp3","理查德 克莱德曼-思乡曲");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-瓦妮莎的微笑.mp3","理查德 克莱德曼-瓦妮莎的微笑");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-忘却的悲伤.mp3","理查德 克莱德曼-忘却的悲伤");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-威尼斯之旅.mp3","理查德 克莱德曼-威尼斯之旅");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-午后的旅行.mp3","理查德 克莱德曼-午后的旅行");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-星空.mp3","理查德 克莱德曼-星空");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-野花.mp3","理查德 克莱德曼-野花");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-英雄交响曲.mp3","理查德 克莱德曼-英雄交响曲");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-永远爱你.mp3","理查德 克莱德曼-永远爱你");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/理查德 克莱德曼-致爱丽丝.mp3","理查德 克莱德曼-致爱丽丝");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/绿钢琴 乐曲.mp3","绿钢琴 乐曲");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/马克西姆-克罗地亚狂想曲.mp3","马克西姆-克罗地亚狂想曲");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/马友友-天鹅 大提琴演奏.mp3","马友友-天鹅 大提琴演奏");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/莫扎特 c大调小星星变奏曲.mp3","莫扎特 c大调小星星变奏曲");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/莫扎特-安魂曲.mp3","莫扎特-安魂曲");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/莫扎特-魔笛.mp3","莫扎特-魔笛");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/莫扎特-土耳其进行曲.mp3","莫扎特-土耳其进行曲");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/莫扎特-小步舞曲.mp3","莫扎特-小步舞曲");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/莫扎特-摇篮曲.mp3","莫扎特-摇篮曲");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/莫扎特-幽默曲.mp3","莫扎特-幽默曲");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/齐普利安·波隆贝斯库-永恒的记忆.mp3","齐普利安·波隆贝斯库-永恒的记忆");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/犬夜叉-哀歌.mp3","犬夜叉-哀歌");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/犬夜叉-跨越时代的思念.mp3","犬夜叉-跨越时代的思念");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/神秘园-莲花.mp3","神秘园-莲花");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/神秘园-夜曲.mp3","神秘园-夜曲");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/神秘园-月亮门.mp3","神秘园-月亮门");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/神秘园之歌-月亮门.mp3","神秘园之歌-月亮门");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/神思者-Project.mp3","神思者-Project");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/神思者-悲情城市.mp3","神思者-悲情城市");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/神思者-故宫的记忆.mp3","神思者-故宫的记忆");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/神思者-海之女神.mp3","神思者-海之女神");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/舒伯特-圣母颂.mp3","舒伯特-圣母颂");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/舒曼-梦幻曲.mp3","舒曼-梦幻曲");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/威尔第 茶花女-普罗旺斯的陆地和海洋.mp3","威尔第 茶花女-普罗旺斯的陆地和海洋");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/乌鸦 片尾曲-月光石 Rurutia.mp3","乌鸦 片尾曲-月光石 Rurutia");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/喜多郎-飞天.mp3","喜多郎-飞天");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/喜多郎-菩提树.mp3","喜多郎-菩提树");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/萧邦-幻想即兴曲.mp3","萧邦-幻想即兴曲");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/徐仁修-森林狂想曲.mp3","徐仁修-森林狂想曲");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/姚斯婷-寂静之声.mp3","姚斯婷-寂静之声");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/约翰 施特劳斯-溜冰圆舞曲.mp3","约翰 施特劳斯-溜冰圆舞曲");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/约翰 施特劳斯-闲聊波尔卡.mp3","约翰 施特劳斯-闲聊波尔卡");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/约翰·施特劳斯-蓝色多瑙河.mp3","约翰·施特劳斯-蓝色多瑙河");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/约翰·施特劳斯-维也纳森林的故事.mp3","约翰·施特劳斯-维也纳森林的故事");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/约纳森-杜鹃圆舞曲.mp3","约纳森-杜鹃圆舞曲");
mkList("https://cloud.hhhnn.com/d/189Family133/音乐视听/纯音乐/宗次郎-故乡的原风景.mp3","宗次郎-故乡的原风景");